export * from './types';
export { GapRegistry } from './registry';
export type { RecordGapInput, ListFilter } from './registry';
export { IssueAutoCreate } from './issueAutoCreate';
export type { IssueDraft, CreateResult } from './issueAutoCreate';
export { SlaEnforcer } from './slaEnforcer';
export type { SlaEnforcerDeps } from './slaEnforcer';
export { computeMetrics } from './metrics';
export type { GapMetrics } from './metrics';
export { loadGapConfig } from './config';
export type { GapConfig } from './config';
export { appendNdjson, readNdjson, ensureDir } from './storage';
export { runQuarterlyAudit, saveAuditReport, renderAuditMarkdown } from './quarterlyAudit';
export type { AuditReport } from './quarterlyAudit';
export { createGapPlugin } from './gapPlugin';
