export const COST_PER_TOKEN = 0.000015;
export const COST_PER_1K_TOKENS = 0.015;

export const THINKING_BUDGET_SIMPLE = 512;
export const THINKING_BUDGET_MODERATE = 2048;
export const THINKING_BUDGET_COMPLEX = 4096;
export const THINKING_BUDGET_DEEP_RESEARCH = 8192;

export const TOKENS_PER_STEP_SIMPLE = 2000;
export const TOKENS_PER_STEP_MODERATE = 4000;
export const TOKENS_PER_STEP_COMPLEX = 8000;
export const TOKENS_PER_STEP_DEEP_RESEARCH = 16000;

export const MIN_TOKENS_PER_AGENT = 2000;
export const MAX_TOKENS_PER_AGENT = 50000;

export const ESTIMATED_DURATION_DEFAULT = 10000;

export const QUALITY_CONFIDENCE_BOOST = 0.1;
export const QUALITY_CONFIDENCE_MAX_LENGTH = 2000;
export const QUALITY_CONFIDENCE_MIN_LENGTH = 50;
