/**
 * WS2 Effect Envelope — the unified contract for every external side effect
 * admitted by the EffectBroker.
 *
 * This module is the single cross-plane contract type for effects. It is
 * imported by @commander/effect-broker (PEP), @commander/kernel (durable
 * ledger), @commander/worker-plane (callers), and @commander/adapter-ops
 * (deploy-unit compensation consumer — not a V2 plane). No ad-hoc effect shape
 * may cross a plane boundary.
 *
 * Invariants (enforced by the broker at admit time):
 *   1. The four identity fields (effect_id, tenant_id, run_id, step_id) are
 *      non-empty and match `^[A-Za-z0-9_-]{1,128}$`.
 *   2. idempotency_key is recomputed by the broker and compared against the
 *      caller-supplied value; mismatch ⇒ REJECTED.
 *   3. status is only written by the broker and the kernel; callers read only.
 */

/**
 * Status of an effect in the broker/kernel ledger.
 *
 * - `admitted`:    admit() succeeded; effect is durable in the kernel ledger.
 * - `executing`:   execute() has dispatched the effect to the executor.
 * - `completed`:   executor returned and kernel.completeEffect() committed.
 * - `failed`:      executor threw or completion was rejected.
 * - `rejected`:    admit() denied the effect (policy/capability/quota/...).
 * - `replayed`:    idempotency key hit an already-completed effect.
 */
export type EffectEnvelopeStatus =
  'admitted' | 'executing' | 'completed' | 'failed' | 'rejected' | 'replayed';

/**
 * Action namespace enum. Actions are dotted strings; the first segment is the
 * namespace. The broker uses the namespace to route to executors and to apply
 * allowlist/rate-limit/quota policy by class.
 *
 * - `http.*`:        outbound HTTP/gRPC calls.
 * - `llm.*`:         LLM provider API calls (completions, embeddings, ...).
 * - `connector.*`:   managed connector operations (Slack, GitHub, DB, ...).
 * - `compensate.*`:  compensation (reverse) effects emitted by the outbox.
 * - `tool.*`:        generic tool invocations that touch external state.
 */
export const EFFECT_ACTION_NAMESPACES = ['http', 'llm', 'connector', 'compensate', 'tool'] as const;

export type EffectActionNamespace = (typeof EFFECT_ACTION_NAMESPACES)[number];

/**
 * Unified effect envelope. All fields use snake_case to match the kernel
 * Postgres schema (commander_effects) and the outbox payload shape; the
 * contracts package keeps this naming convention for cross-plane stability.
 */
export interface EffectEnvelope {
  /** Globally unique effect ID (UUID v4). Generated by the caller or broker. */
  effect_id: string;
  /** Tenant ID. Must match the capability token's tenantId. */
  tenant_id: string;
  /** Run ID. References kernel runs table. */
  run_id: string;
  /** Step ID. References kernel steps table. */
  step_id: string;
  /** Action type, e.g. "http.post" | "llm.complete" | "connector.slack.postMessage" | "compensate.http.delete". */
  action: string;
  /** Action payload. Structure is determined by `action`; the executor parses it. */
  payload: Record<string, unknown>;
  /**
   * Idempotency key. Caller-supplied; broker recomputes
   * SHA-256(run_id + step_id + action + canonical(payload)) and rejects
   * mismatches. Same key ⇒ broker returns cached response.
   */
  idempotency_key: string;
  /** Written by broker/kernel only. Callers must not set this on admit(). */
  status: EffectEnvelopeStatus;
}

/** Extract the namespace (first dotted segment) of an action string. */
export function actionNamespace(action: string): EffectActionNamespace | null {
  const idx = action.indexOf('.');
  const head = idx === -1 ? action : action.slice(0, idx);
  return (EFFECT_ACTION_NAMESPACES as readonly string[]).includes(head)
    ? (head as EffectActionNamespace)
    : null;
}

/** Identity-field charset. Used by the broker to validate envelope fields. */
export const EFFECT_ID_PATTERN = /^[A-Za-z0-9_-]{1,128}$/;

/**
 * Validate the four identity fields of an envelope. Returns true iff all are
 * non-empty and match the allowed charset. Does NOT validate idempotency_key
 * (the broker recomputes it) or status (broker/kernel-owned).
 */
export function isValidEffectEnvelopeIdentity(envelope: {
  effect_id: string;
  tenant_id: string;
  run_id: string;
  step_id: string;
}): boolean {
  return (
    EFFECT_ID_PATTERN.test(envelope.effect_id) &&
    EFFECT_ID_PATTERN.test(envelope.tenant_id) &&
    EFFECT_ID_PATTERN.test(envelope.run_id) &&
    EFFECT_ID_PATTERN.test(envelope.step_id)
  );
}
