import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: [
      'tests/runtime/agentRuntime.test.ts',
      'tests/runtime/semanticCache.test.ts',
      'tests/httpServer.test.ts',
      'tests/runtime/criticalPath.test.ts',
      'tests/runtime/entropyGater.test.ts',
      'tests/runtime/e2e.test.ts',
      'tests/runtime/htmlReport.test.ts',
      'tests/runtime/metaTool.test.ts',
      'tests/runtime/metaLearner.test.ts',
      'tests/runtime/modelRouter.test.ts',
      'tests/runtime/speculativeExecutor.test.ts',
      'tests/runtime/toolCalling.test.ts',
      'tests/runtime/toolRetriever.test.ts',
      'tests/runtime/compensationRegistry.test.ts',
      'tests/runtime/llmRetry.test.ts',
      'tests/runtime/stepErrorBoundary.test.ts',
      'tests/telos/providerPool.test.ts',
      'tests/telos/telosOrchestrator.test.ts',
      'tests/telos/tokenSentinel.test.ts',
      'tests/intelligence/costAggregator.test.ts',
      'tests/runtime/circuitBreaker.test.ts',
      'tests/runtime/deadLetterQueue.test.ts',
      'tests/runtime/cycleDetector.test.ts',
      'tests/runtime/credentialManager.test.ts',
      'tests/runtime/agentHandoff.test.ts',
      'tests/runtime/agentInbox.test.ts',
      'tests/runtime/tokenBenchmark.test.ts',
      'tests/runtime/tokenMeasurement.test.ts',
      'tests/tools-security.test.ts',
      'tests/sandbox/lane.test.ts',
      'tests/runtime/toolPlanner.test.ts',
      'tests/runtime/dagConverter.test.ts',
      'tests/runtime/processCrashSafety.test.ts',
      'tests/runtime/runRecovery.test.ts',
      'tests/runtime/stepTimeoutManager.test.ts',
      'tests/runtime/providerFallbackChain.test.ts',
      'tests/ultimate/topologyRouter.test.ts',
      'tests/ultimate/workCoordinator.test.ts',
      'tests/ultimate/workQueueStore.test.ts',
      'tests/ultimate/subAgentGuard.test.ts',
      'tests/ultimate/tenantWorkCoordinatorRegistry.test.ts',
      'tests/ultimate/chaos/m2-6-multiprocess-claim.test.ts',
      'tests/ultimate/chaos/m2-6-crash-resume.test.ts',
      'tests/ultimate/chaos/m2-6-compensation-fail.test.ts',
      'tests/ultimate/chaos/m2-6-tenant-independence.test.ts',
    ],
    environment: 'node',
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      include: ['src/**/*.ts'],
      exclude: ['src/**/*.test.ts', 'src/**/*.d.ts'],
      thresholds: {
        statements: 60,
        branches: 80,
        functions: 70,
        lines: 60,
      },
    },
  },
});
