import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: [
      'tests/runtime/agentRuntime.test.ts',
      'tests/httpServer.test.ts',
      'tests/runtime/criticalPath.test.ts',
      'tests/runtime/entropyGater.test.ts',
      'tests/runtime/e2e.test.ts',
      'tests/runtime/htmlReport.test.ts',
      'tests/runtime/metaTool.test.ts',
      'tests/runtime/messageBus.test.ts',
      'tests/runtime/metaLearner.test.ts',
      'tests/runtime/modelRouter.test.ts',
      'tests/runtime/speculativeExecutor.test.ts',
      'tests/runtime/toolCalling.test.ts',
      'tests/runtime/toolRetriever.test.ts',
      'tests/runtime/compensationRegistry.test.ts',
      'tests/runtime/llmRetry.test.ts',
      'tests/runtime/stepErrorBoundary.test.ts',
      'tests/telos/providerPool.test.ts',
      'tests/telos/telosOrchestrator.test.ts',
      'tests/telos/tokenSentinel.test.ts',
      'tests/runtime/circuitBreaker.test.ts',
      'tests/runtime/deadLetterQueue.test.ts',
      'tests/runtime/cycleDetector.test.ts',
      'tests/runtime/credentialManager.test.ts',
      'tests/runtime/agentHandoff.test.ts',
      'tests/runtime/agentInbox.test.ts',
    ],
    environment: 'node',
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      include: ['src/**/*.ts'],
      exclude: ['src/**/*.test.ts', 'src/**/*.d.ts'],
      thresholds: {
        statements: 20,
        branches: 15,
        functions: 20,
        lines: 20,
      },
    },
  },
});
