export interface OutboxMessage { id: string; topic: string; key: string; payload: Record<string, unknown>; claimToken?: string; attempts: number; }
export interface OutboxPort { claimOutbox(limit: number, now?: Date): Promise<OutboxMessage[]>; markOutboxPublished(id: string, claimToken: string): Promise<boolean>; }
export interface EventPublisher { publish(message: { topic: string; key: string; payload: Record<string, unknown> }): Promise<void>; }
/** At-least-once publisher: only the owner of a live claim token may acknowledge delivery. */
export class OutboxPublisher {
  constructor(private readonly outbox: OutboxPort, private readonly publisher: EventPublisher) {}
  async publishOnce(limit = 100): Promise<{ published: number; failed: number }> { let published = 0; let failed = 0; for (const message of await this.outbox.claimOutbox(limit)) { if (!message.claimToken) { failed++; continue; } try { await this.publisher.publish({ topic: message.topic, key: message.key, payload: message.payload }); if (await this.outbox.markOutboxPublished(message.id, message.claimToken)) published++; else failed++; } catch { failed++; } } return { published, failed }; }
}
export interface EvidenceEvent { id: string; type: string; occurredAt: string; actor: string; tenantId: string; runId: string; stepId?: string; payload: Record<string, unknown>; }
export interface EvidenceTimeline { runId: string; tenantId: string; startedAt?: string; terminalAt?: string; events: EvidenceEvent[]; gaps: string[]; }
export function buildEvidenceTimeline(events: EvidenceEvent[]): EvidenceTimeline { const ordered = [...events].sort((a,b) => a.occurredAt.localeCompare(b.occurredAt)); const first = ordered[0]; const gaps: string[] = []; if (!first) gaps.push('no_events'); else { if (first.type !== 'run.created') gaps.push('missing_run_created'); if (!ordered.some((event) => event.type.startsWith('run.succeeded') || event.type.startsWith('run.failed'))) gaps.push('missing_terminal_event'); if (ordered.some((event) => !event.actor)) gaps.push('missing_actor'); } const terminal = [...ordered].reverse().find((event: EvidenceEvent) => event.type === 'run.succeeded' || event.type === 'run.failed'); return { runId: first?.runId ?? '', tenantId: first?.tenantId ?? '', startedAt: first?.occurredAt, terminalAt: terminal?.occurredAt, events: ordered, gaps }; }
export interface SloDefinition { id: string; target: number; windowMs: number; selector: (sample: SloSample) => boolean; }
export interface SloSample { at: number; success: boolean; durationMs?: number; labels?: Record<string,string>; }
export interface SloReport { id: string; total: number; successes: number; availability: number; target: number; compliant: boolean; burnRate: number; }
export function evaluateSlo(definition: SloDefinition, samples: SloSample[], now = Date.now()): SloReport { const selected = samples.filter((sample) => sample.at >= now - definition.windowMs && definition.selector(sample)); const successes = selected.filter((sample) => sample.success).length; const availability = selected.length === 0 ? 1 : successes / selected.length; const errorBudget = Math.max(1 - definition.target, Number.EPSILON); return { id: definition.id, total: selected.length, successes, availability, target: definition.target, compliant: availability >= definition.target, burnRate: (1 - availability) / errorBudget }; }
