/**
 * ci-database-scope.ts — admission control for scripts that MUTATE a database.
 *
 * PostgreSQL roles are cluster-level objects: creating or re-password-ing one
 * affects every database in that cluster, including production databases that
 * happen to share it. So none of the following is authorization to change them:
 *
 *   - the presence of DATABASE_URL,
 *   - CI=true,
 *   - a loopback / private-network target address,
 *   - a marker row the caller could have written itself.
 *
 * Before this module existed, `ci-restore-deploy-gate-roles.ts` reset six role
 * passwords to the role name itself with no guard beyond "DATABASE_URL is set",
 * and `test:deploy-gates` invoked it as an ordinary acceptance step.
 *
 * This module implements the admission conditions that can be evaluated from
 * inside the process:
 *
 *   1. an explicit opt-in (never inferred from any ambient signal),
 *   2. a run-scoped instance identifier minted by the provisioner,
 *   3. a run-scoped provisioner credential,
 *   4. a loopback/private target address,
 *   5. per-run role passwords supplied through the environment.
 *
 * RESIDUAL GAP (recorded, not silently assumed): this does not prove that the
 * provisioner owns the instance exclusively. Doing that requires a provisioner
 * interface that this repository does not have, so a determined caller that can
 * set all of the above environment variables can still reach the mutation path.
 * These checks remove the implicit path and the public default passwords; they
 * are not a substitute for a real provisioner-owned instance identity.
 */

/** Explicit opt-in. Absence means "no" — it is never inferred. */
export const MUTATION_OPT_IN_ENV = 'COMMANDER_CI_INSTANCE_MUTATION';

/** Run-scoped instance identifier minted by the provisioner for this run. */
export const INSTANCE_ID_ENV = 'COMMANDER_CI_INSTANCE_ID';

/** Run-scoped credential the provisioner minted for this run. */
export const PROVISION_TOKEN_ENV = 'COMMANDER_CI_PROVISION_TOKEN';

export const MIN_INSTANCE_ID_LENGTH = 8;
export const MIN_PROVISION_TOKEN_LENGTH = 16;
export const MIN_ROLE_PASSWORD_LENGTH = 16;

/**
 * The six deploy-gate runtime roles. Fixed and whitelisted: never interpolated
 * from user input, so an `ALTER ROLE` identifier can never be attacker-chosen.
 */
export const DEPLOY_GATE_ROLES = [
  'commander_owner',
  'commander_app',
  'commander_tenant_authority',
  'commander_scheduler',
  'commander_worker',
  'commander_adapter_ops',
] as const;

export type DeployGateRole = (typeof DEPLOY_GATE_ROLES)[number];

/** Environment variable that must carry each role's run-scoped password. */
export const ROLE_PASSWORD_ENV: Record<DeployGateRole, string> = {
  commander_owner: 'COMMANDER_CI_PASSWORD_COMMANDER_OWNER',
  commander_app: 'COMMANDER_CI_PASSWORD_COMMANDER_APP',
  commander_tenant_authority: 'COMMANDER_CI_PASSWORD_COMMANDER_TENANT_AUTHORITY',
  commander_scheduler: 'COMMANDER_CI_PASSWORD_COMMANDER_SCHEDULER',
  commander_worker: 'COMMANDER_CI_PASSWORD_COMMANDER_WORKER',
  commander_adapter_ops: 'COMMANDER_CI_PASSWORD_COMMANDER_ADAPTER_OPS',
};

/**
 * Passwords that must never be accepted: the historical defaults (the role name
 * itself, and the generic service-container password).
 */
export const FORBIDDEN_ROLE_PASSWORDS = new Set<string>([
  'commander',
  ...DEPLOY_GATE_ROLES,
  'password',
  'changeme',
  'postgres',
]);

/**
 * Allowed password charset. Passwords are generated by the provisioner, so a
 * strict allowlist is available — and it removes SQL-literal quoting as a risk
 * surface entirely (no quotes, no backslashes, no control characters).
 */
export const PASSWORD_CHARSET = /^[A-Za-z0-9._~!@%^*+=:-]+$/;

/**
 * The exact privilege vector each role must have after the reset. Checking the
 * privileges — not merely that the password changed — is the point: a reset
 * that silently grants CREATEROLE or BYPASSRLS is a privilege escalation.
 */
export interface ExpectedRolePrivileges {
  login: boolean;
  superuser: boolean;
  createDb: boolean;
  createRole: boolean;
  inherit: boolean;
  replication: boolean;
  bypassRls: boolean;
}

export const EXPECTED_ROLE_PRIVILEGES: Record<DeployGateRole, ExpectedRolePrivileges> = {
  commander_owner: {
    login: true,
    superuser: false,
    createDb: false,
    createRole: true,
    inherit: true,
    replication: false,
    bypassRls: true,
  },
  commander_app: {
    login: true,
    superuser: false,
    createDb: false,
    createRole: false,
    inherit: false,
    replication: false,
    bypassRls: false,
  },
  commander_tenant_authority: {
    login: true,
    superuser: false,
    createDb: false,
    createRole: false,
    inherit: false,
    replication: false,
    bypassRls: false,
  },
  commander_scheduler: {
    login: true,
    superuser: false,
    createDb: false,
    createRole: false,
    inherit: false,
    replication: false,
    bypassRls: true,
  },
  commander_worker: {
    login: true,
    superuser: false,
    createDb: false,
    createRole: false,
    inherit: false,
    replication: false,
    bypassRls: false,
  },
  commander_adapter_ops: {
    login: true,
    superuser: false,
    createDb: false,
    createRole: false,
    inherit: false,
    replication: false,
    bypassRls: false,
  },
};

const LOOPBACK_HOSTS = new Set(['localhost', '127.0.0.1', '::1', '[::1]']);

/** Loopback or RFC1918/ULA address. A necessary condition, never sufficient. */
export function isLoopbackOrPrivateHost(host: string): boolean {
  const normalized = host.trim().toLowerCase();
  if (!normalized) return false;
  if (LOOPBACK_HOSTS.has(normalized)) return true;
  if (/^127\./.test(normalized)) return true;
  if (/^10\./.test(normalized)) return true;
  if (/^192\.168\./.test(normalized)) return true;
  if (/^172\.(1[6-9]|2\d|3[01])\./.test(normalized)) return true;
  if (/^\[?(fc|fd)[0-9a-f]{2}:/.test(normalized)) return true;
  return false;
}

export function hostOfDsn(dsn: string): string | undefined {
  try {
    return new URL(dsn).hostname || undefined;
  } catch {
    return undefined;
  }
}

/**
 * Evaluate the admission conditions for a mutating CI step.
 * Returns the list of unmet conditions; an empty list means admitted.
 */
export function assertProvisionedCiInstance(
  env: NodeJS.ProcessEnv = process.env,
  dsn?: string,
): string[] {
  const failures: string[] = [];

  if (env[MUTATION_OPT_IN_ENV] !== 'yes') {
    failures.push(
      `CI_INSTANCE_MUTATION_NOT_AUTHORIZED: set ${MUTATION_OPT_IN_ENV}=yes for a provisioned instance`,
    );
  }

  const instanceId = env[INSTANCE_ID_ENV]?.trim() ?? '';
  if (instanceId.length < MIN_INSTANCE_ID_LENGTH) {
    failures.push(
      `CI_INSTANCE_ID_REQUIRED: ${INSTANCE_ID_ENV} must be a run-scoped provisioner identifier`,
    );
  }

  const token = env[PROVISION_TOKEN_ENV]?.trim() ?? '';
  if (token.length < MIN_PROVISION_TOKEN_LENGTH) {
    failures.push(
      `CI_PROVISION_TOKEN_REQUIRED: ${PROVISION_TOKEN_ENV} must be a run-scoped provisioner credential`,
    );
  }

  if (dsn !== undefined) {
    const host = hostOfDsn(dsn);
    if (!host || !isLoopbackOrPrivateHost(host)) {
      failures.push(
        'CI_TARGET_NOT_ISOLATED: the target host is not loopback/private; refusing to mutate it',
      );
    }
  }

  return failures;
}

/**
 * Resolve a role's run-scoped password from the environment.
 * There is no default: a missing password is a failure, and the historical
 * public defaults are explicitly rejected.
 */
export function resolveRolePassword(
  role: DeployGateRole,
  env: NodeJS.ProcessEnv = process.env,
): { password?: string; failures: string[] } {
  const envName = ROLE_PASSWORD_ENV[role];
  const value = env[envName];
  if (value === undefined || value.trim().length === 0) {
    return { failures: [`CI_ROLE_PASSWORD_REQUIRED: ${envName} is not set`] };
  }
  const password = value.trim();
  const failures: string[] = [];
  // Check the known-public defaults first: that is the more precise diagnosis,
  // and some of them (e.g. "commander_owner") are also shorter than the minimum.
  if (FORBIDDEN_ROLE_PASSWORDS.has(password.toLowerCase())) {
    failures.push(`CI_ROLE_PASSWORD_INSECURE: ${envName} is a known public default`);
  }
  if (password.length < MIN_ROLE_PASSWORD_LENGTH) {
    failures.push(
      `CI_ROLE_PASSWORD_TOO_SHORT: ${envName} must be at least ${MIN_ROLE_PASSWORD_LENGTH} characters`,
    );
  }
  if (!PASSWORD_CHARSET.test(password)) {
    failures.push(
      `CI_ROLE_PASSWORD_CHARSET_INVALID: ${envName} contains characters outside the allowed set`,
    );
  }
  if (failures.length > 0) return { failures };
  return { password, failures };
}

/**
 * Render a password as a PostgreSQL string literal.
 *
 * This is defence in depth, not the primary control: `resolveRolePassword`
 * already restricts the value to a charset that contains no quote, backslash,
 * or control character, so this function can only ever wrap an already-safe
 * value. NUL bytes are rejected outright.
 */
export function sqlLiteral(value: string): string {
  if (value.includes('\u0000')) {
    throw new Error('SQL_LITERAL_NUL_REJECTED');
  }
  if (!PASSWORD_CHARSET.test(value)) {
    throw new Error('SQL_LITERAL_CHARSET_REJECTED');
  }
  return `'${value}'`;
}

/** Fail fast with a single, stable, secret-free message. */
export function formatAdmissionFailure(failures: readonly string[]): string {
  return `CI_DATABASE_MUTATION_REFUSED:\n  - ${failures.join('\n  - ')}`;
}
