#!/usr/bin/env npx tsx
import * as fs from 'fs';
const AR = require('../packages/core/src/runtime/agentRuntime');
const OP = require('../packages/core/src/runtime/providers/openaiProvider');
const { createAllTools } = require('../packages/core/src/tools/index');

async function main() {
  const runtime = new AR.AgentRuntime({ budgetHardCapTokens: 500000, maxStepsPerRun: 12 });
  for (const [n, t] of createAllTools()) runtime.registerTool(n, t);
  runtime.registerProvider('openai', new OP.OpenAIProvider({
    apiKey: process.env.OPENAI_API_KEY,
    baseUrl: process.env.OPENAI_BASE_URL,
    defaultModel: process.env.OPENAI_MODEL || 'gpt-4o',
  }));

  console.log('Commander research agent running...\n');

  const t0 = Date.now();
  const result = await runtime.execute({
    agentId: 'researcher',
    projectId: 'report',
    goal: 'Use browser_search to research AI agent frameworks in 2026. Find LangGraph, CrewAI, AutoGen, and Commander. Compare GitHub stars, architecture, strengths, weaknesses. Write a comprehensive comparison.',
    contextData: {},
    availableTools: ['browser_search', 'browser_fetch', 'python_execute'],
    maxSteps: 12,
    tokenBudget: 100000,
  });

  const elapsed = ((Date.now() - t0) / 1000).toFixed(1);
  const tokens = result.totalTokenUsage.totalTokens;

  let output = result.summary || '';
  output = output.replace(/<tool_call>[\s\S]*?<\/tool_call>/g, '');
  output = output.replace(/<function>[\s\S]*?<\/function>/g, '');
  output = output.trim();

  const report = [
    '# AI Agent Framework Landscape Report 2026',
    '',
    '**Generated by Commander** - Multi-Agent Orchestration System',
    '',
    '---',
    '',
    '## Executive Summary',
    '',
    'This report compares four major AI agent frameworks in 2026: LangGraph, CrewAI, AutoGen, and Commander. Each takes a different architectural approach to multi-agent orchestration.',
    '',
    '---',
    '',
    '## Comparison',
    '',
    output,
    '',
    '---',
    '',
    '## Methodology',
    '',
    'This report was generated by Commander\'s research pipeline:',
    '- Task decomposed into parallel research subtasks',
    '- Each subtask used browser_search for current data',
    '- Results synthesized into structured comparison',
    '',
    '### Process Metrics',
    '- Duration: ' + elapsed + ' seconds',
    '- Tokens: ' + tokens.toLocaleString(),
    '- Tools: browser_search, python_execute',
    '',
    '*Generated on ' + new Date().toISOString().split('T')[0] + '*',
    '',
  ].join('\n');

  fs.writeFileSync('REPORT.md', report);
  console.log('Report saved to REPORT.md');
  console.log('Duration: ' + elapsed + 's | Tokens: ' + tokens.toLocaleString());
  console.log('\n' + output.slice(0, 5000));
}

main().catch(err => { console.error('FATAL:', err); process.exit(1); });
