export const MAX_DIAGNOSTIC_CODE_LENGTH = 96;

const DIAGNOSTIC_CODES = [
  'COMMANDER_MIGRATION_FAILED',
  'TASK1_CLOSURE_BASELINE_REQUIRED',
  'TENANT_CUTOVER_OWNER_JOB_LOG_UNAVAILABLE',
  'HELM_TENANT_CUTOVER_FAILED',
  'TENANT_CUTOVER_OWNER_JOB_FAILED',
  'TENANT_CUTOVER_COMMAND_FAILED',
  'TENANT_CUTOVER_COMMAND_OUTPUT_LIMIT',
  'TENANT_CUTOVER_COMMAND_TIMEOUT',
  'TENANT_CUTOVER_COMMAND_TERMINATION_UNCONFIRMED',
  'TENANT_CUTOVER_COMMAND_TIMEOUT_POLICY_INVALID',
  'TENANT_CUTOVER_HELM_COMMAND_FAILED',
  'TENANT_CUTOVER_ROLLOUT_RESOURCE_FAILED',
  'TENANT_CUTOVER_ROLLOUT_RESOURCE_UNCLASSIFIED',
  'TENANT_CUTOVER_HELM_RESTORE_COMMAND_FAILED',
  'TENANT_CUTOVER_HELM_POST_RENDER_COMMAND_FAILED',
  'TENANT_CUTOVER_HELM_PROJECTION_COMMAND_FAILED',
  'TENANT_CUTOVER_RELEASE_PROJECTION_INVALID',
  'TENANT_CUTOVER_RELEASE_PROJECTION_CREATE_FAILED',
  'TENANT_CUTOVER_KUBECTL_COMMAND_FAILED',
  'TENANT_CUTOVER_KUBECTL_LOGS_COMMAND_FAILED',
] as const;

const ALLOWED_DIAGNOSTIC_CODES = new Set<string>(DIAGNOSTIC_CODES);

export function isAllowedHelmDiagnosticCode(value: string): boolean {
  return value.length <= MAX_DIAGNOSTIC_CODE_LENGTH && ALLOWED_DIAGNOSTIC_CODES.has(value);
}
