/**
 * Commander completion — Shell autocompletion scripts.
 *
 * Usage:
 *   commander completion bash     Print bash completion script
 *   commander completion zsh      Print zsh completion script
 *   commander completion fish     Print fish completion script
 *   commander completion install  Auto-detect shell and install
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { $, section, kv } from './_shared';

// ============================================================================
// Command & flag definitions for completion
// ============================================================================

const COMMANDS: Record<string, string[]> = {
  run: [],
  plan: [],
  watch: [],
  company: [],
  goal: ['--provider=', '--mode=', '--budget=', '--max-rounds='],
  swarm: ['--provider=', '--mode=', '--max-depth=', '--max-workers=', '--budget=', '--max-rounds='],
  drive: ['--mode=', '--iterations=', '--verbose'],
  workers: [],
  status: [],
  config: ['set', 'show', 'list-providers', 'list-models', 'test'],
  doctor: [],
  mode: ['plan', 'read-only', 'suggest', 'auto-edit', 'full-auto'],
  history: ['view', 'delete', 'prune'],
  skill: ['list', 'ls', 'view', 'create', 'pin', 'unpin', 'delete', 'rm', 'curate'],
  review: ['--commit', '--branch', '--json', '--base=', '--guidelines='],
  workflow: [
    'ls',
    'list',
    'run',
    'schedule',
    'unschedule',
    'pause',
    'resume',
    'history',
    'log',
    'create',
    'daemon',
    'start',
    'stop',
  ],

  quickstart: ['--check'],
  completion: ['bash', 'zsh', 'fish', 'install'],
  gui: [],
  tui: [],
};

const TOP_LEVEL = Object.keys(COMMANDS);

// ============================================================================
// Bash completion
// ============================================================================

function generateBash(): string {
  const cmdCases = TOP_LEVEL.map((cmd) => {
    const subcmds = COMMANDS[cmd];
    if (subcmds.length === 0) return `        ${cmd}) COMPREPLY=() ;;`;
    return `        ${cmd}) COMPREPLY=($(compgen -W "${subcmds.join(' ')}" -- "$cur")) ;;`;
  }).join('\n');

  return `#!/usr/bin/env bash
# Commander CLI completion — generated by \`commander completion bash\`
# Install: commander completion install
# Or: source <(commander completion bash)

_commander_completions() {
  local cur prev commands
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  commands="${TOP_LEVEL.join(' ')}"

  # Top-level command completion
  if [[ \${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "\${commands} --help --version" -- "$cur") )
    return 0
  fi

  # Subcommand / flag completion
  local cmd="\${COMP_WORDS[1]}"
  case "$cmd" in
${cmdCases}
    *)
      COMPREPLY=()
      ;;
  esac

  return 0
}

complete -F _commander_completions commander
`;
}

// ============================================================================
// Zsh completion
// ============================================================================

function generateZsh(): string {
  const cmdEntries = TOP_LEVEL.map((cmd) => {
    const subcmds = COMMANDS[cmd];
    if (subcmds.length === 0) {
      return `    "${cmd}"`;
    }
    return `    "${cmd}[${cmd} command]::subcommand:(${subcmds.join(' ')})"`;
  }).join('\n');

  return `#compdef commander
# Commander CLI completion — generated by \`commander completion zsh\`
# Install: commander completion install
# Or: source <(commander completion zsh)

_commander() {
  local -a commands

  commands=(
${cmdEntries}
    "--help[Show help]"
    "--version[Show version]"
  )

  _arguments -C \\
    '1:command:->commands' \\
    '*:arg:->args'

  case $state in
    commands)
      _describe -t commands 'commander command' commands
      ;;
    args)
      case $words[1] in
${TOP_LEVEL.map((cmd) => {
  const subcmds = COMMANDS[cmd];
  if (subcmds.length === 0) return '';
  return `        ${cmd})\n          _describe -t subcommands '${cmd} subcommand' (${subcmds.map((s) => `"${s}"`).join(' ')})\n          ;;`;
})
  .filter(Boolean)
  .join('\n')}
      esac
      ;;
  esac
}

_commander "$@"
`;
}

// ============================================================================
// Fish completion
// ============================================================================

function generateFish(): string {
  const lines: string[] = [
    '# Commander CLI completion — generated by `commander completion fish`',
    '# Install: commander completion install',
    '# Or: commander completion fish | source',
    '',
    '# Disable file completion by default',
    'complete -c commander -f',
    '',
    '# Top-level commands',
  ];

  for (const cmd of TOP_LEVEL) {
    lines.push(`complete -c commander -n '__fish_use_subcommand' -a ${cmd}`);
  }

  lines.push('');
  lines.push('# Global flags');
  lines.push('complete -c commander -n \'__fish_use_subcommand\' -l help -d "Show help"');
  lines.push('complete -c commander -n \'__fish_use_subcommand\' -l version -d "Show version"');
  lines.push('');

  // Subcommands
  for (const [cmd, subcmds] of Object.entries(COMMANDS)) {
    if (subcmds.length === 0) continue;
    lines.push(`# ${cmd} subcommands/flags`);
    for (const sub of subcmds) {
      if (sub.startsWith('--')) {
        // Flag
        const flagName = sub.replace(/=$/, '');
        const desc = `Flag for ${cmd}`;
        lines.push(
          `complete -c commander -n '__fish_seen_subcommand_from ${cmd}' -l ${flagName.replace('--', '')} -d "${desc}"`,
        );
      } else {
        // Subcommand
        lines.push(`complete -c commander -n '__fish_seen_subcommand_from ${cmd}' -a ${sub}`);
      }
    }
    lines.push('');
  }

  return lines.join('\n') + '\n';
}

// ============================================================================
// Install helper
// ============================================================================

function detectShell(): string {
  const shell = process.env.SHELL || '';
  if (shell.includes('zsh')) return 'zsh';
  if (shell.includes('bash')) return 'bash';
  if (shell.includes('fish')) return 'fish';
  return 'bash';
}

function getInstallPath(shell: string): string {
  const home = process.env.HOME || process.env.USERPROFILE || '~';
  switch (shell) {
    case 'zsh':
      return path.join(home, '.commander-completion.zsh');
    case 'bash':
      return path.join(home, '.commander-completion.bash');
    case 'fish':
      return path.join(home, '.config', 'fish', 'completions', 'commander.fish');
    default:
      return path.join(home, `.commander-completion.${shell}`);
  }
}

function getRcFile(shell: string): string {
  const home = process.env.HOME || process.env.USERPROFILE || '~';
  switch (shell) {
    case 'zsh':
      return path.join(home, '.zshrc');
    case 'bash':
      return path.join(home, '.bashrc');
    case 'fish':
      return path.join(home, '.config', 'fish', 'config.fish');
    default:
      return '';
  }
}

// ============================================================================
// Main command
// ============================================================================

export async function cmdCompletion(args: string[]) {
  const subcmd = args[0] || 'install';
  const shell = subcmd === 'install' ? detectShell() : subcmd;

  if (!['bash', 'zsh', 'fish', 'install'].includes(subcmd)) {
    console.error(`  ${$.red}Unknown shell:${$.reset} "${subcmd}"`);
    console.log(`  ${$.dim}Usage: commander completion [bash|zsh|fish|install]${$.reset}\n`);
    return;
  }

  if (subcmd === 'install') {
    const detected = detectShell();
    const script =
      detected === 'zsh' ? generateZsh() : detected === 'fish' ? generateFish() : generateBash();
    const installPath = getInstallPath(detected);
    const rcFile = getRcFile(detected);

    // Write completion script
    const dir = path.dirname(installPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(installPath, script);

    section('AUTOCOMPLETION INSTALLED');
    kv('Shell', detected, $.cyan);
    kv('Script', installPath, $.dim);

    // Check if already sourced in rc
    if (rcFile && fs.existsSync(rcFile)) {
      const rcContent = fs.readFileSync(rcFile, 'utf-8');
      if (rcContent.includes('commander-completion') || rcContent.includes(installPath)) {
        console.log(`\n  ${$.green}✓${$.reset} Already configured in ${$.dim}${rcFile}${$.reset}`);
        console.log(`  ${$.dim}Restart your shell or run: source ${rcFile}${$.reset}\n`);
        return;
      }
    }

    // Add source line to rc
    const sourceLine =
      detected === 'fish'
        ? `source ${installPath}`
        : `[ -f ${installPath} ] && source ${installPath}`;

    console.log(`\n  ${$.bold}Add this to your ${rcFile}:${$.reset}\n`);
    console.log(`    ${$.gray}${sourceLine}${$.reset}`);
    console.log(`\n  ${$.dim}Or run:${$.reset}`);
    console.log(`    ${$.gray}echo '${sourceLine}' >> ${rcFile}${$.reset}`);
    console.log(`    ${$.gray}source ${rcFile}${$.reset}\n`);
    return;
  }

  // Print script to stdout
  let script: string;
  switch (shell) {
    case 'bash':
      script = generateBash();
      break;
    case 'zsh':
      script = generateZsh();
      break;
    case 'fish':
      script = generateFish();
      break;
    default:
      script = generateBash();
  }
  process.stdout.write(script);
}
