/**
 * PostgreSQL-authoritative authentication state for horizontally scaled API
 * replicas. Replaces the JSON-file / Redis / SQLite / in-memory authorities
 * previously used by the API layer.
 *
 * Design:
 *  - `commander_auth_users` is the global identity store (username / email /
 *    OIDC bindings are globally unique, case-insensitive).
 *  - `commander_auth_api_keys` carries an optional `tenant_id`; the hash is
 *    globally unique so pre-auth lookup works across replicas. RLS (non-forced)
 *    scopes tenant-aware reads when the caller sets `app.tenant_scope`.
 *  - `commander_auth_refresh_tokens` supports single-use consumption via an
 *    atomic `UPDATE ... RETURNING`.
 *  - `commander_auth_failures` and `commander_auth_rate_limits` are atomic
 *    upsert counters shared by every API replica (no process-local state).
 *  - Only `commander_app` receives DML; scheduler / worker / adapter-ops /
 *    tenant-authority / PUBLIC are revoked.
 */
export const KERNEL_AUTH_PERSISTENCE_SQL = [
  'CREATE TABLE commander_auth_users (',
  '  id TEXT PRIMARY KEY,',
  '  username TEXT NOT NULL,',
  '  email TEXT NOT NULL,',
  '  password_hash TEXT NOT NULL,',
  "  role TEXT NOT NULL CHECK (role IN ('super_admin','admin','developer','operator','auditor','viewer')),",
  '  oidc_issuer TEXT,',
  '  oidc_subject TEXT,',
  '  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),',
  '  last_login_at TIMESTAMPTZ,',
  '  CHECK ((oidc_issuer IS NULL) = (oidc_subject IS NULL))',
  ');',
  'CREATE UNIQUE INDEX commander_auth_users_username_ci_uidx',
  '  ON commander_auth_users (lower(username));',
  'CREATE UNIQUE INDEX commander_auth_users_email_ci_uidx',
  '  ON commander_auth_users (lower(email));',
  'CREATE UNIQUE INDEX commander_auth_users_oidc_uidx',
  '  ON commander_auth_users (oidc_issuer, oidc_subject)',
  '  WHERE oidc_issuer IS NOT NULL;',
  '',
  'CREATE TABLE commander_auth_api_keys (',
  '  id TEXT PRIMARY KEY,',
  '  user_id TEXT REFERENCES commander_auth_users(id) ON DELETE CASCADE,',
  '  name TEXT NOT NULL,',
  '  prefix TEXT NOT NULL,',
  '  key_hash TEXT NOT NULL UNIQUE,',
  '  scopes TEXT[] NOT NULL CHECK (cardinality(scopes) > 0),',
  '  tenant_id TEXT,',
  '  enabled BOOLEAN NOT NULL DEFAULT true,',
  '  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),',
  '  revoked_at TIMESTAMPTZ,',
  '  CHECK ((enabled AND revoked_at IS NULL) OR (NOT enabled AND revoked_at IS NOT NULL))',
  ');',
  'CREATE INDEX commander_auth_api_keys_tenant_created_idx',
  '  ON commander_auth_api_keys (tenant_id, created_at DESC);',
  '',
  'CREATE TABLE commander_auth_refresh_tokens (',
  '  jti TEXT PRIMARY KEY,',
  '  user_id TEXT NOT NULL REFERENCES commander_auth_users(id) ON DELETE CASCADE,',
  '  expires_at TIMESTAMPTZ NOT NULL,',
  '  revoked_at TIMESTAMPTZ,',
  '  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()',
  ');',
  'CREATE INDEX commander_auth_refresh_tokens_user_idx',
  '  ON commander_auth_refresh_tokens (user_id);',
  'CREATE INDEX commander_auth_refresh_tokens_expiry_idx',
  '  ON commander_auth_refresh_tokens (expires_at);',
  '',
  'CREATE TABLE commander_auth_failures (',
  '  failure_key TEXT PRIMARY KEY,',
  '  count INTEGER NOT NULL CHECK (count > 0),',
  '  first_failure_at TIMESTAMPTZ NOT NULL,',
  '  last_failure_at TIMESTAMPTZ NOT NULL,',
  '  locked_until TIMESTAMPTZ,',
  '  CHECK (last_failure_at >= first_failure_at)',
  ');',
  'CREATE INDEX commander_auth_failures_cleanup_idx',
  '  ON commander_auth_failures (last_failure_at, locked_until);',
  '',
  'CREATE TABLE commander_auth_rate_limits (',
  '  bucket_key TEXT PRIMARY KEY,',
  '  count INTEGER NOT NULL CHECK (count >= 0),',
  '  reset_at TIMESTAMPTZ NOT NULL',
  ');',
  'CREATE INDEX commander_auth_rate_limits_expiry_idx',
  '  ON commander_auth_rate_limits (reset_at);',
  '',
  'ALTER TABLE commander_auth_users OWNER TO commander_owner;',
  'ALTER TABLE commander_auth_api_keys OWNER TO commander_owner;',
  'ALTER TABLE commander_auth_refresh_tokens OWNER TO commander_owner;',
  'ALTER TABLE commander_auth_failures OWNER TO commander_owner;',
  'ALTER TABLE commander_auth_rate_limits OWNER TO commander_owner;',
  '',
  'REVOKE ALL PRIVILEGES ON TABLE',
  '  commander_auth_users,',
  '  commander_auth_api_keys,',
  '  commander_auth_refresh_tokens,',
  '  commander_auth_failures,',
  '  commander_auth_rate_limits',
  'FROM PUBLIC, commander_scheduler, commander_worker, commander_adapter_ops;',
  '',
  'DO $$',
  'BEGIN',
  "  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'commander_tenant_authority') THEN",
  "    EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE commander_auth_users, commander_auth_api_keys, commander_auth_refresh_tokens, commander_auth_failures, commander_auth_rate_limits FROM commander_tenant_authority';",
  '  END IF;',
  'END $$;',
  '',
  'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE',
  '  commander_auth_users,',
  '  commander_auth_api_keys,',
  '  commander_auth_refresh_tokens,',
  '  commander_auth_failures,',
  '  commander_auth_rate_limits',
  'TO commander_app;',
  '',
  '-- Defense-in-depth tenant isolation for API keys. Pre-auth hash lookup runs',
  '-- without a tenant scope (tenant_id is derived FROM the key); once a caller',
  "-- sets app.tenant_scope, only that tenant's keys (and unbound keys) are",
  '-- visible to commander_app. Not FORCED so migration-owner recovery flows and',
  '-- the global pre-auth lookup keep working.',
  'ALTER TABLE commander_auth_api_keys ENABLE ROW LEVEL SECURITY;',
  'DROP POLICY IF EXISTS commander_auth_api_keys_tenant_isolation ON commander_auth_api_keys;',
  'CREATE POLICY commander_auth_api_keys_tenant_isolation ON commander_auth_api_keys',
  '  FOR ALL TO PUBLIC',
  '  USING (',
  "    current_setting('app.tenant_scope', true) = ''",
  '    OR tenant_id IS NULL',
  "    OR tenant_id = ANY(string_to_array(current_setting('app.tenant_scope', true), ','))",
  '  )',
  '  WITH CHECK (',
  "    current_setting('app.tenant_scope', true) = ''",
  '    OR tenant_id IS NULL',
  "    OR tenant_id = ANY(string_to_array(current_setting('app.tenant_scope', true), ','))",
  '  );',
].join('\n');
