apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commander.fullname" . }}-api
  labels:
    {{- include "commander.labels" . | nindent 4 }}
type: Opaque
stringData:
  COMMANDER_API_KEY: {{ .Values.api.secrets.COMMANDER_API_KEY | default (randAlphaNum 32) | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commander.fullname" . }}-worker
  labels:
    {{- include "commander.labels" . | nindent 4 }}
type: Opaque
stringData:
  COMMANDER_WORKER_AUTH_TOKEN: {{ .Values.worker.secrets.COMMANDER_WORKER_AUTH_TOKEN | default (randAlphaNum 32) | quote }}
