/**
 * SLOPage — Public service-level objectives dashboard.
 *
 * Displays the committed SLO targets and the latest measured baseline. The data
 * is sourced from `docs/baselines/slo-baseline.2026-07-06.json`, which is
 * regenerated by `scripts/bench-slo-baseline.ts` and enforced by the daily
 * `slo-bench.yml` workflow.
 */
import { useEffect, useState } from 'react';
import { Activity, CheckCircle, AlertTriangle, XCircle } from 'lucide-react';
import { fetchSLOStatus } from '../api';
import type { SLOStatus, SLOMeasurement } from '../types';

function statusIcon(status: SLOMeasurement['status']) {
  if (status === 'passing') return <CheckCircle size={16} color="var(--accent-green)" />;
  if (status === 'breached') return <XCircle size={16} color="var(--accent-red)" />;
  return <AlertTriangle size={16} color="var(--accent-amber)" />;
}

function statusClass(status: SLOMeasurement['status']) {
  if (status === 'passing') return 'slo-tag slo-tag-passing';
  if (status === 'breached') return 'slo-tag slo-tag-breached';
  return 'slo-tag slo-tag-risk';
}

export function SLOPage() {
  const [status, setStatus] = useState<SLOStatus | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    fetchSLOStatus()
      .then((data) => {
        if (!cancelled) {
          setStatus(data);
          setError(null);
        }
      })
      .catch((err: Error) => {
        if (!cancelled) {
          setError(err.message);
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  if (loading) {
    return (
      <div className="page">
        <div className="page-head">
          <span className="section-label">Operations</span>
          <h1>Service Level Objectives</h1>
        </div>
        <div className="card" style={{ padding: '32px', textAlign: 'center' }}>
          <span style={{ color: 'var(--text-muted)' }}>Loading SLO baseline…</span>
        </div>
      </div>
    );
  }

  if (error || !status) {
    return (
      <div className="page">
        <div className="page-head">
          <span className="section-label">Operations</span>
          <h1>Service Level Objectives</h1>
        </div>
        <div className="card" style={{ padding: '24px', textAlign: 'center' }}>
          <p style={{ color: 'var(--accent-amber)', fontSize: '0.8rem', marginBottom: '8px' }}>
            {error ?? 'No SLO data available'}
          </p>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.72rem' }}>
            Run <code>pnpm run bench:slo-baseline</code> to regenerate the baseline snapshot.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="page">
      <div className="page-head">
        <div>
          <div className="section-label">Operations</div>
          <h1>Service Level Objectives</h1>
        </div>
        <p className="page-desc">
          Public SLO commitments and measured baseline. Updated daily by the SLO benchmark runner.
          Last measurement: {new Date(status.updatedAt).toLocaleString()}.
        </p>
      </div>

      <div className="metric-row">
        <div className="metric-card">
          <div className="metric-label">Overall Status</div>
          <div
            className="metric-value"
            style={{ display: 'flex', alignItems: 'center', gap: '8px' }}
          >
            {statusIcon(status.overall)}
            <span style={{ textTransform: 'capitalize' }}>{status.overall.replace('_', ' ')}</span>
          </div>
        </div>
        <div className="metric-card">
          <div className="metric-label">API Success Rate</div>
          <div className="metric-value">{status.apiSuccessRate.toFixed(2)}%</div>
        </div>
        <div className="metric-card">
          <div className="metric-label">P95 Plan Latency</div>
          <div className="metric-value">{status.p95PlanLatencyMs.toFixed(0)} ms</div>
        </div>
      </div>

      <div className="card" style={{ marginTop: '16px' }}>
        <div className="card-head">
          <Activity size={16} />
          <span>Measurements</span>
        </div>
        <table className="data-table">
          <thead>
            <tr>
              <th>SLO</th>
              <th>Target</th>
              <th>Actual</th>
              <th>Status</th>
              <th>Evidence</th>
            </tr>
          </thead>
          <tbody>
            {status.measurements.map((m) => (
              <tr key={m.name}>
                <td style={{ fontWeight: 500 }}>{m.name}</td>
                <td>{m.target}</td>
                <td>{m.actual}</td>
                <td>
                  <span className={statusClass(m.status)}>{m.status.replace('_', ' ')}</span>
                </td>
                <td style={{ color: 'var(--text-muted)', fontSize: '0.72rem' }}>
                  {m.evidence ?? '—'}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
