/**
 * Skill System — agentskills.io compatible, MetaLearner-bridged.
 *
 * Each skill is a directory in .commander/skills/<name>/ containing SKILL.md
 * with YAML frontmatter (agentskills.io spec) and optional scripts/, references/.
 * Skills teach the agent how to use tools effectively.
 *
 * Three loading levels (progressive disclosure):
 *   Level 0: Skill names only (~3K tokens for full library)
 *   Level 1: Full SKILL.md content for relevant skills
 *   Level 2: Reference files on demand
 */

import { reportSilentFailure } from '../silentFailureReporter';
export type {
  SkillSource,
  SkillCategory,
  SkillMetadata,
  Skill,
  SkillFrontmatter,
  DisclosureLevel,
  SkillCatalogEntry,
  SkillSearchQuery,
  CuratorReport,
  SkillDef,
} from './types';

export { SkillViewTool } from './skillViewTool';

export { SkillStore } from './skillStore';
export { SkillManager } from './skillManager';
export { MetaLearnerBridge } from './metaLearnerBridge';
export { SkillInjector } from './skillInjector';
export {
  SkillCurator,
  jaccardSimilarity,
  nameSimilarity,
  descriptionSimilarity,
  tagSimilarity,
  computeSimilarity,
  findSimilarPairs,
  buildMergePrompt,
} from './skillCurator';
export type { SimilarityWeights, MergeStrategy, MergeResult } from './skillCurator';
export {
  computeQualityScore,
  computeDeterministicScore,
  evaluateWithRubric,
  buildRubricPrompt,
} from './skillQualityScorer';
export type {
  QualityFactor,
  QualityScoreResult,
  LLMRubricConfig,
  RubricCriterion,
} from './skillQualityScorer';
export { scanSkillContent, rejectReason } from './skillSecurityScanner';
export type { SecurityScanResult, SecurityWarning } from './skillSecurityScanner';

// ============================================================================
// Legacy backward-compatible API — delegates to the new SkillManager singleton
// ============================================================================

import * as fs from 'fs';
import * as path from 'path';
import { getGlobalLogger } from '../logging';
import { SkillStore } from './skillStore';
import { SkillManager } from './skillManager';
import { SkillInjector } from './skillInjector';
import { SkillCurator } from './skillCurator';
import type { SkillDef as LegacySkillDef } from './types';
import { MetaLearnerBridge } from './metaLearnerBridge';
import { getMetaLearner } from '../selfEvolution/metaLearner';
import { createTenantAwareSingleton } from '../runtime/tenantAwareSingleton';

const LEGACY_SKILLS_DIR = path.join(process.cwd(), '.commander', 'skills');

const skillSystemSingleton = createTenantAwareSingleton(() => {
  const store = new SkillStore();
  const manager = new SkillManager(store);
  store
    .migrateFromJson()
    .catch((e) =>
      getGlobalLogger().warn('Skills', 'Migration failed', { error: (e as Error)?.message }),
    );
  return {
    manager,
    injector: new SkillInjector(manager),
    curator: new SkillCurator(manager),
    bridge: new MetaLearnerBridge(getMetaLearner(), manager),
  };
});

function getManager(): SkillManager {
  return skillSystemSingleton.get().manager;
}

function getBridge(): MetaLearnerBridge {
  return skillSystemSingleton.get().bridge;
}

/** Legacy: create a skill from explicit fields. */
export function createSkill(
  name: string,
  description: string,
  tools: string[],
  prompt: string,
): LegacySkillDef {
  const now = new Date().toISOString();
  const skillDef: LegacySkillDef = {
    name,
    description,
    tools,
    prompt,
    usageCount: 0,
    createdAt: now,
    updatedAt: now,
  };

  getManager()
    .create(name, prompt, {
      category: 'general',
      tags: [],
      source: 'user',
      qualityScore: 0.5,
      usageCount: 0,
      avgSuccessRate: 0.5,
      autoGenerated: false,
      createdAt: now,
      updatedAt: now,
    })
    .catch((e) =>
      getGlobalLogger().warn('Skills', 'Failed to create skill', { error: (e as Error)?.message }),
    );

  return skillDef;
}

/** Legacy: load a single skill by name (JSON format fallback). */
export function loadSkill(name: string): LegacySkillDef | null {
  try {
    const jsonPath = path.join(LEGACY_SKILLS_DIR, `${name}.json`);
    if (fs.existsSync(jsonPath)) {
      return JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
    }
  } catch (err) {
    reportSilentFailure(err, 'index:146');
    return null;
  }
  return null;
}

/** Legacy: list all skills as SkillDef array. */
export function listSkills(): LegacySkillDef[] {
  try {
    if (!fs.existsSync(LEGACY_SKILLS_DIR)) return [];
    return fs
      .readdirSync(LEGACY_SKILLS_DIR)
      .filter((f) => f.endsWith('.json'))
      .map((f) => {
        try {
          return JSON.parse(
            fs.readFileSync(path.join(LEGACY_SKILLS_DIR, f), 'utf-8'),
          ) as LegacySkillDef;
        } catch (err) {
          reportSilentFailure(err, 'index:165');
          return null;
        }
      })
      .filter((s): s is LegacySkillDef => s !== null)
      .sort((a, b) => b.usageCount - a.usageCount);
  } catch (err) {
    reportSilentFailure(err, 'index:172');
    return [];
  }
}

/** Legacy: build system prompt from skills (Level 0 only). */
export function buildSkillsPrompt(maxLevel: 0 | 1 | 2 = 0): string {
  if (maxLevel === 0) {
    const skills = listSkills();
    if (skills.length === 0) return '';
    return (
      '### Available Skills\n\n' + skills.map((s) => `- ${s.name}: ${s.description}`).join('\n')
    );
  }
  return ''; // Level 1+ requires async SkillManager
}

/** Legacy: record usage of a skill. */
export function recordSkillUsage(name: string): void {
  getManager()
    .recordUsage(name, true)
    .catch((e) =>
      getGlobalLogger().warn('Skills', 'Failed to record usage', { error: (e as Error)?.message }),
    );
}

/** Legacy: delete a skill. */
export function deleteSkill(name: string): boolean {
  getManager()
    .delete(name)
    .catch((e) =>
      getGlobalLogger().warn('Skills', 'Failed to delete skill', { error: (e as Error)?.message }),
    );
  try {
    const jsonPath = path.join(LEGACY_SKILLS_DIR, `${name}.json`);
    if (fs.existsSync(jsonPath)) {
      fs.unlinkSync(jsonPath);
    }
  } catch (err) {
    reportSilentFailure(err, 'index:211');
    return false;
  }
  return true;
}

export interface SkillSystem {
  manager: SkillManager;
  injector: SkillInjector;
  curator: SkillCurator;
  bridge: MetaLearnerBridge;
}

export function createSkillSystem(): SkillSystem {
  const store = new SkillStore();
  const manager = new SkillManager(store);
  const injector = new SkillInjector(manager);
  const curator = new SkillCurator(manager);
  const bridge = new MetaLearnerBridge(getMetaLearner(), manager);
  return { manager, injector, curator, bridge };
}

export function getSkillSystem(): SkillSystem {
  const sys = skillSystemSingleton.get();
  return {
    manager: sys.manager,
    injector: sys.injector,
    curator: sys.curator,
    bridge: sys.bridge,
  };
}

export function resetSkillSystem(): void {
  skillSystemSingleton.reset();
}
