"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MetaLearnerBridge = void 0;
const STRATEGY_NAMES = ['SEQUENTIAL', 'PARALLEL', 'HANDOFF', 'MAGENTIC', 'CONSENSUS'];
class MetaLearnerBridge {
    constructor(metaLearner, skillManager) {
        this.metaLearner = metaLearner;
        this.skillManager = skillManager;
    }
    async extractSkills() {
        const newSkills = [];
        const thompsonPriors = this.getThompsonPriors();
        for (const [taskType, priors] of thompsonPriors) {
            const bestIdx = priors.map((p) => p.mean).indexOf(Math.max(...priors.map((p) => p.mean)));
            const bestScore = priors[bestIdx].mean;
            const totalTrials = priors[bestIdx].totalTrials;
            if (totalTrials >= 5 && bestScore > 0.7) {
                const strategyName = STRATEGY_NAMES[bestIdx];
                const skillName = `strategy-${taskType}-${strategyName}`.toLowerCase();
                const existing = await this.skillManager.search({ text: skillName, limit: 1 });
                if (existing.length > 0)
                    continue;
                const generatedFrom = `strategy-${taskType}-${strategyName}`;
                const skill = await this.skillManager.create(skillName, this.generateSkillContent(taskType, strategyName, bestScore), {
                    category: 'strategy',
                    tags: [taskType.toLowerCase(), strategyName.toLowerCase(), 'auto-generated'],
                    source: 'learned',
                    qualityScore: bestScore,
                    usageCount: totalTrials,
                    avgSuccessRate: bestScore,
                    autoGenerated: true,
                    generatedFrom,
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                });
                newSkills.push(skill);
            }
        }
        return newSkills;
    }
    generateSkillContent(taskType, strategy, confidence) {
        return [
            `# strategy-${taskType}-${strategy}`,
            '',
            '## Description',
            `Automatically discovered strategy for ${taskType} tasks using ${strategy} topology.`,
            `Confidence: ${(confidence * 100).toFixed(0)}% across validated trials.`,
            '',
            '## When to Use',
            `- Task type matches: ${taskType}`,
            `- The ${strategy} topology has shown consistently positive results for similar tasks`,
            '',
            '## Steps',
            `1. Configure ${strategy} orchestration topology`,
            '2. Decompose the task using recursive atomizer',
            `3. Execute subtasks with ${strategy} coordination pattern`,
            '4. Synthesize results',
            '',
            '## Tools Required',
            '- Agent delegation',
            '- File system tools for persistence',
            '- Web search for research tasks',
        ].join('\n');
    }
    getThompsonPriors() {
        const result = new Map();
        const taskTypes = this.metaLearner.getTrackedTaskTypes();
        for (const taskType of taskTypes) {
            const scores = this.metaLearner.getStrategyScores(taskType);
            result.set(taskType, scores.map((s) => ({ mean: s.score, totalTrials: s.trials })));
        }
        return result;
    }
}
exports.MetaLearnerBridge = MetaLearnerBridge;
