import type { Skill } from './types';
import type { SkillManager } from './skillManager';
import type { MetaLearner } from '../selfEvolution/metaLearner';

const STRATEGY_NAMES = ['SEQUENTIAL', 'PARALLEL', 'HANDOFF', 'MAGENTIC', 'CONSENSUS'];

export class MetaLearnerBridge {
  private metaLearner: MetaLearner;
  private skillManager: SkillManager;

  constructor(metaLearner: MetaLearner, skillManager: SkillManager) {
    this.metaLearner = metaLearner;
    this.skillManager = skillManager;
  }

  async extractSkills(): Promise<Skill[]> {
    const newSkills: Skill[] = [];
    const thompsonPriors = this.getThompsonPriors();

    for (const [taskType, priors] of thompsonPriors) {
      const bestIdx = priors.map(p => p.mean).indexOf(Math.max(...priors.map(p => p.mean)));
      const bestScore = priors[bestIdx].mean;
      const totalTrials = priors[bestIdx].totalTrials;

      if (totalTrials >= 5 && bestScore > 0.7) {
        const strategyName = STRATEGY_NAMES[bestIdx];
        const skillName = `strategy-${taskType}-${strategyName}`.toLowerCase();

        const existing = await this.skillManager.search({ text: skillName, limit: 1 });
        if (existing.length > 0) continue;

        const generatedFrom = `strategy-${taskType}-${strategyName}`;
        const skill = await this.skillManager.create(
          skillName,
          this.generateSkillContent(taskType, strategyName, bestScore),
          {
            category: 'strategy',
            tags: [taskType.toLowerCase(), strategyName.toLowerCase(), 'auto-generated'],
            source: 'learned',
            qualityScore: bestScore,
            usageCount: totalTrials,
            avgSuccessRate: bestScore,
            autoGenerated: true,
            generatedFrom,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
        );
        newSkills.push(skill);
      }
    }

    return newSkills;
  }

  private generateSkillContent(taskType: string, strategy: string, confidence: number): string {
    return [
      `# strategy-${taskType}-${strategy}`,
      '',
      '## Description',
      `Automatically discovered strategy for ${taskType} tasks using ${strategy} topology.`,
      `Confidence: ${(confidence * 100).toFixed(0)}% across validated trials.`,
      '',
      '## When to Use',
      `- Task type matches: ${taskType}`,
      `- The ${strategy} topology has shown consistently positive results for similar tasks`,
      '',
      '## Steps',
      `1. Configure ${strategy} orchestration topology`,
      '2. Decompose the task using recursive atomizer',
      `3. Execute subtasks with ${strategy} coordination pattern`,
      '4. Synthesize results',
      '',
      '## Tools Required',
      '- Agent delegation',
      '- File system tools for persistence',
      '- Web search for research tasks',
    ].join('\n');
  }

  private getThompsonPriors(): Map<string, Array<{ mean: number; totalTrials: number }>> {
    const result = new Map<string, Array<{ mean: number; totalTrials: number }>>();
    const taskTypes = this.metaLearner.getTrackedTaskTypes();
    for (const taskType of taskTypes) {
      const scores = this.metaLearner.getStrategyScores(taskType);
      result.set(taskType, scores.map(s => ({ mean: s.score, totalTrials: s.trials })));
    }
    return result;
  }
}
