import type {
  Skill,
  SkillMetadata,
  SkillCatalogEntry,
  SkillSearchQuery,
  SkillCategory,
} from './types';
import { SkillStore } from './skillStore';
import { getGlobalLogger } from '../logging';
import { computeQualityScore } from './skillQualityScorer';
import { scanSkillContent, rejectReason } from './skillSecurityScanner';

export class SkillManager {
  private store: SkillStore;
  private cache: Map<string, Skill> = new Map();
  private catalogCache: SkillCatalogEntry[] | null = null;

  constructor(store: SkillStore) {
    this.store = store;
  }

  // ========================================================================
  // CRUD
  // ========================================================================

  async create(name: string, content: string, metadata: Partial<SkillMetadata>): Promise<Skill> {
    const now = new Date().toISOString();
    const id = name
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');
    const skill: Skill = {
      id,
      name: id,
      description: content.split('\n')[0]?.replace(/^#\s*/, '').trim() || name,
      content,
      tools: [],
      metadata: {
        category: metadata.category ?? 'general',
        tags: metadata.tags ?? [],
        source: metadata.source ?? 'learned',
        qualityScore: metadata.qualityScore ?? 0.5,
        usageCount: metadata.usageCount ?? 0,
        avgSuccessRate: metadata.avgSuccessRate ?? 0.5,
        autoGenerated: metadata.autoGenerated ?? false,
        pinned: metadata.pinned ?? false,
        generatedFrom: metadata.generatedFrom,
        createdAt: metadata.createdAt ?? now,
        updatedAt: now,
      },
    };

    if (!metadata.category && !skill.description) {
      const firstLine = content.split('\n')[0]?.replace(/^#\s*/, '').trim();
      skill.description = firstLine || skill.name;
    }

    // Security scan skill content before persisting
    const scanResult = scanSkillContent(skill.name, skill.content, skill.tools);
    const rejection = rejectReason(scanResult, skill.name);
    if (rejection) {
      throw new Error(rejection);
    }

    // Auto-score quality based on observable characteristics
    skill.metadata.qualityScore = (await computeQualityScore(skill)).total;

    await this.store.save(skill);
    this.cache.set(skill.id, skill);
    this.catalogCache = null;
    return skill;
  }

  async get(name: string): Promise<Skill | null> {
    const id = name.toLowerCase().replace(/[^a-z0-9-]/g, '-');
    if (this.cache.has(id)) return this.cache.get(id)!;
    const skill = await this.store.load(name);
    if (skill) this.cache.set(skill.id, skill);
    return skill;
  }

  async update(name: string, updates: Partial<Skill>): Promise<Skill> {
    const existing = await this.get(name);
    if (!existing) throw new Error(`Skill "${name}" not found`);

    const updated: Skill = {
      ...existing,
      ...updates,
      id: existing.id,
      metadata: {
        ...existing.metadata,
        ...(updates.metadata ?? {}),
        updatedAt: new Date().toISOString(),
      },
    };

    await this.store.save(updated);
    this.cache.set(updated.id, updated);
    this.catalogCache = null;
    return updated;
  }

  async delete(name: string): Promise<boolean> {
    const id = name.toLowerCase().replace(/[^a-z0-9-]/g, '-');
    this.cache.delete(id);
    this.catalogCache = null;
    return this.store.delete(name);
  }

  // ========================================================================
  // Search & Discovery
  // ========================================================================

  async search(query: SkillSearchQuery): Promise<SkillCatalogEntry[]> {
    let results = await this.list();

    if (query.text) {
      const lower = query.text.toLowerCase();
      results = results.filter(
        (s) =>
          s.name.toLowerCase().includes(lower) ||
          s.description.toLowerCase().includes(lower) ||
          s.tags.some((t) => t.toLowerCase().includes(lower)),
      );
    }

    if (query.category) {
      results = results.filter((s) => s.category === query.category);
    }

    if (query.tags && query.tags.length > 0) {
      results = results.filter((s) => query.tags!.every((t) => s.tags.includes(t)));
    }

    if (query.source) {
      results = results.filter((s) => s.source === query.source);
    }

    if (query.minQuality !== undefined) {
      results = results.filter((s) => s.qualityScore >= query.minQuality!);
    }

    results.sort((a, b) => b.qualityScore - a.qualityScore);

    if (query.limit) {
      results = results.slice(0, query.limit);
    }

    return results;
  }

  async list(category?: SkillCategory): Promise<SkillCatalogEntry[]> {
    if (this.catalogCache && !category) return this.catalogCache;

    const names = await this.store.list();
    const entries: SkillCatalogEntry[] = [];

    for (const name of names) {
      const skill = this.cache.get(name.toLowerCase().replace(/[^a-z0-9-]/g, '-'));
      if (skill) {
        if (category && skill.metadata.category !== category) continue;
        entries.push(this.toCatalogEntry(skill));
        continue;
      }
    }

    const cachedNames = new Set(entries.map((e) => e.name));
    for (const name of names) {
      if (cachedNames.has(name)) continue;
      const skill = await this.store.load(name);
      if (!skill) continue;
      if (category && skill.metadata.category !== category) continue;
      this.cache.set(skill.id, skill);
      entries.push(this.toCatalogEntry(skill));
    }

    entries.sort((a, b) => b.qualityScore - a.qualityScore);
    return entries;
  }

  async suggestForTask(goal: string, limit = 3): Promise<SkillCatalogEntry[]> {
    const keywords = this.extractKeywords(goal);
    if (keywords.length === 0) return [];

    const allSkills = await this.list();
    const scored = allSkills.map((entry) => {
      const searchText = `${entry.name} ${entry.description} ${entry.tags.join(' ')}`.toLowerCase();
      let score = 0;
      const matchCount = keywords.filter((kw) => searchText.includes(kw)).length;
      score = Math.min(1, matchCount / keywords.length);

      return { entry, score };
    });

    return scored
      .filter((s) => s.score > 0)
      .sort((a, b) => {
        const scoreDiff = b.score - a.score;
        if (Math.abs(scoreDiff) > 0.1) return scoreDiff;
        return b.entry.qualityScore - a.entry.qualityScore;
      })
      .slice(0, limit)
      .map((s) => s.entry);
  }

  // ========================================================================
  // Usage Tracking
  // ========================================================================

  async recordUsage(name: string, success: boolean): Promise<void> {
    const skill = await this.get(name);
    if (!skill) return;

    skill.metadata.usageCount++;
    const total = skill.metadata.usageCount;
    const currentAvg = skill.metadata.avgSuccessRate;
    skill.metadata.avgSuccessRate = (currentAvg * (total - 1) + (success ? 1 : 0)) / total;
    skill.metadata.updatedAt = new Date().toISOString();

    await this.store.save(skill);
    this.cache.set(skill.id, skill);
    this.catalogCache = null;
  }

  // ========================================================================
  // Pin / Unpin
  // ========================================================================

  async setPinned(name: string, pinned: boolean): Promise<void> {
    const skill = await this.get(name);
    if (!skill) throw new Error(`Skill "${name}" not found`);
    skill.metadata.pinned = pinned;
    skill.metadata.updatedAt = new Date().toISOString();
    await this.store.save(skill);
    this.cache.set(skill.id, skill);
    this.catalogCache = null;
  }

  async isPinned(name: string): Promise<boolean> {
    const skill = await this.get(name);
    return skill?.metadata.pinned ?? false;
  }

  // ========================================================================
  // Utilities
  // ========================================================================

  /** Get the on-disk directory path for a skill (delegates to SkillStore). */
  getSkillPath(name: string): string {
    return this.store.getSkillPath(name);
  }

  async getCatalog(): Promise<SkillCatalogEntry[]> {
    return this.list();
  }

  async exportSkill(name: string): Promise<string | null> {
    const skill = await this.get(name);
    if (!skill) return null;

    const fm = {
      name: skill.name,
      description: skill.description,
      license: 'MIT',
      compatibility: 'commander',
      version: '1.0',
      metadata: {
        category: skill.metadata.category,
        tags: skill.metadata.tags,
        source: skill.metadata.source,
        quality_score: skill.metadata.qualityScore,
        usage_count: skill.metadata.usageCount,
        avg_success_rate: skill.metadata.avgSuccessRate,
      },
      'allowed-tools': skill.tools.length > 0 ? skill.tools.join(' ') : undefined,
    };

    const yamlLines: string[] = [];
    for (const [key, value] of Object.entries(fm)) {
      if (value === undefined) continue;
      if (typeof value === 'object') {
        yamlLines.push(`${key}:`);
        for (const [sk, sv] of Object.entries(value as Record<string, unknown>)) {
          if (sv === undefined) continue;
          if (Array.isArray(sv)) {
            yamlLines.push(`  ${sk}: [${sv.join(', ')}]`);
          } else {
            yamlLines.push(`  ${sk}: ${sv}`);
          }
        }
      } else {
        yamlLines.push(`${key}: ${value}`);
      }
    }

    return `---\n${yamlLines.join('\n')}\n---\n\n${skill.content}`;
  }

  async warmCache(): Promise<void> {
    const skills = await this.store.loadAll();
    for (const skill of skills) {
      this.cache.set(skill.id, skill);
    }
    this.catalogCache = null;
  }

  invalidateCache(): void {
    this.cache.clear();
    this.catalogCache = null;
  }

  private toCatalogEntry(skill: Skill): SkillCatalogEntry {
    return {
      name: skill.name,
      description: skill.description,
      category: skill.metadata.category,
      tags: skill.metadata.tags,
      usageCount: skill.metadata.usageCount,
      qualityScore: skill.metadata.qualityScore,
      pinned: skill.metadata.pinned,
      source: skill.metadata.source,
    };
  }

  private extractKeywords(text: string): string[] {
    const stopWords = new Set([
      'the',
      'a',
      'an',
      'is',
      'are',
      'was',
      'were',
      'be',
      'been',
      'being',
      'have',
      'has',
      'had',
      'do',
      'does',
      'did',
      'will',
      'would',
      'could',
      'should',
      'may',
      'might',
      'shall',
      'can',
      'need',
      'dare',
      'ought',
      'used',
      'to',
      'of',
      'in',
      'for',
      'on',
      'with',
      'at',
      'by',
      'from',
      'as',
      'into',
      'through',
      'during',
      'before',
      'after',
      'above',
      'below',
      'between',
      'out',
      'off',
      'over',
      'under',
      'again',
      'further',
      'then',
      'once',
      'here',
      'there',
      'when',
      'where',
      'why',
      'how',
      'all',
      'each',
      'every',
      'both',
      'few',
      'more',
      'most',
      'other',
      'some',
      'such',
      'no',
      'nor',
      'not',
      'only',
      'own',
      'same',
      'so',
      'than',
      'too',
      'very',
      'just',
      'because',
      'but',
      'and',
      'or',
      'if',
      'while',
      'that',
      'this',
      'these',
      'those',
      'it',
      'its',
      'what',
      'which',
      'who',
      'whom',
    ]);

    return text
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, ' ')
      .split(/\s+/)
      .filter((w) => w.length > 2 && !stopWords.has(w))
      .slice(0, 10);
  }
}
