/**
 * Skill System Types — agentskills.io SKILL.md standard format.
 * Skills are markdown files with YAML frontmatter teaching agents how to
 * use tools effectively. Supports 3-level progressive disclosure for
 * token-efficient context management.
 */

export type SkillSource = 'builtin' | 'learned' | 'community' | 'user';

export type SkillCategory =
  | 'coding'
  | 'research'
  | 'analysis'
  | 'writing'
  | 'strategy'
  | 'general';

export interface SkillMetadata {
  category: SkillCategory;
  tags: string[];
  source: SkillSource;
  qualityScore: number;
  usageCount: number;
  avgSuccessRate: number;
  autoGenerated: boolean;
  pinned: boolean;
  generatedFrom?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Skill {
  id: string;
  name: string;
  description: string;
  content: string;
  tools: string[];
  metadata: SkillMetadata;
}

/** agentskills.io YAML frontmatter — snake_case fields match the spec. */
export interface SkillFrontmatter {
  name: string;
  description: string;
  license?: string;
  version?: string;
  author?: string;
  compatibility?: string;
  metadata: {
    category: string;
    tags: string[];
    source?: string;
    quality_score?: number;
    usage_count?: number;
    avg_success_rate?: number;
    auto_generated?: boolean;
    pinned?: boolean;
    generated_from?: string;
  };
  'allowed-tools'?: string;
}

export type DisclosureLevel = 0 | 1 | 2;

export interface SkillCatalogEntry {
  name: string;
  description: string;
  category: SkillCategory;
  tags: string[];
  usageCount: number;
  qualityScore: number;
  pinned: boolean;
  source?: SkillSource;
}

export interface SkillSearchQuery {
  text?: string;
  category?: SkillCategory;
  tags?: string[];
  source?: SkillSource;
  minQuality?: number;
  limit?: number;
}

export interface CuratorReport {
  archived: string[];
  pruned: string[];
  consolidated: string[];
  qualityDropped: string[];
  totalBefore: number;
  totalAfter: number;
  snapshotPath?: string;
  runTimestamp: string;
  totalArchived: number;
}

/** Legacy SkillDef — kept for backward compatibility. */
export interface SkillDef {
  name: string;
  description: string;
  tools: string[];
  prompt: string;
  usageCount: number;
  createdAt: string;
  updatedAt: string;
}
